{
  "total_count": 17,
  "incomplete_results": false,
  "items": [
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/38491",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/38491/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/38491/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/38491/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/38491",
      "id": 618421559,
      "node_id": "MDU6SXNzdWU2MTg0MjE1NTk=",
      "number": 38491,
      "title": "DISABLED ParallelWorkersTest.testParallelWorkersShutdownFun ",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 693805995,
          "node_id": "MDU6TGFiZWw2OTM4MDU5OTU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20onnx",
          "name": "module: onnx",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.onnx"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-05-14T17:45:34Z",
      "updated_at": "2020-05-14T17:45:40Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/169923/workflows/d66ca278-d55c-462b-96cb-55623ce713f7/jobs/5472514/steps\r\n\r\n```\r\nMay 14 07:37:27 =================================== FAILURES ===================================\r\nMay 14 07:37:27 ______________ ParallelWorkersTest.testParallelWorkersShutdownFun ______________\r\nMay 14 07:37:27 \r\nMay 14 07:37:27 self = <caffe2.python.parallel_workers_test.ParallelWorkersTest testMethod=testParallelWorkersShutdownFun>\r\nMay 14 07:37:27 \r\nMay 14 07:37:27     def testParallelWorkersShutdownFun(self):\r\nMay 14 07:37:27         workspace.ResetWorkspace()\r\nMay 14 07:37:27     \r\nMay 14 07:37:27         queue = create_queue()\r\nMay 14 07:37:27         dummy_worker = create_worker(queue, lambda worker_id: str(worker_id))\r\nMay 14 07:37:27         workspace.FeedBlob('data', 'not shutdown')\r\nMay 14 07:37:27     \r\nMay 14 07:37:27         def shutdown_fun():\r\nMay 14 07:37:27             workspace.FeedBlob('data', 'shutdown')\r\nMay 14 07:37:27     \r\nMay 14 07:37:27         worker_coordinator = parallel_workers.init_workers(\r\nMay 14 07:37:27             dummy_worker, shutdown_fun=shutdown_fun\r\nMay 14 07:37:27         )\r\nMay 14 07:37:27         worker_coordinator.start()\r\nMay 14 07:37:27     \r\nMay 14 07:37:27 >       self.assertTrue(worker_coordinator.stop())\r\nMay 14 07:37:27 E       AssertionError: False is not true\r\nMay 14 07:37:27 \r\nMay 14 07:37:27 ../.local/lib/python3.6/site-packages/caffe2/python/parallel_workers_test.py:116: AssertionError\r\nMay 14 07:37:27 ----------------------------- Captured stdout call -----------------------------\r\n```\n\ncc @ezyang @gchanan @zou3519 @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/38834",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/38834/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/38834/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/38834/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/38834",
      "id": 622144602,
      "node_id": "MDU6SXNzdWU2MjIxNDQ2MDI=",
      "number": 38834,
      "title": "DISABLED test_reduce (__main__.TestNCCL)",
      "user": {
        "login": "pritamdamania87",
        "id": 9958665,
        "node_id": "MDQ6VXNlcjk5NTg2NjU=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/9958665?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/pritamdamania87",
        "html_url": "https://github.com/pritamdamania87",
        "followers_url": "https://api.github.com/users/pritamdamania87/followers",
        "following_url": "https://api.github.com/users/pritamdamania87/following{/other_user}",
        "gists_url": "https://api.github.com/users/pritamdamania87/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/pritamdamania87/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pritamdamania87/subscriptions",
        "organizations_url": "https://api.github.com/users/pritamdamania87/orgs",
        "repos_url": "https://api.github.com/users/pritamdamania87/repos",
        "events_url": "https://api.github.com/users/pritamdamania87/events{/privacy}",
        "received_events_url": "https://api.github.com/users/pritamdamania87/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 2,
      "created_at": "2020-05-20T23:23:46Z",
      "updated_at": "2020-06-01T16:57:51Z",
      "closed_at": null,
      "author_association": "NONE",
      "body": "https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28226//console\r\nhttps://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28233//console\r\nhttps://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28234//console\n\ncc @ezyang @gchanan @zou3519",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/39457",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/39457/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/39457/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/39457/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/39457",
      "id": 630212173,
      "node_id": "MDU6SXNzdWU2MzAyMTIxNzM=",
      "number": 39457,
      "title": "DISABLED test_backward_node_failure (__main__.TensorPipeAgentDistAutogradTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1986434179,
          "node_id": "MDU6TGFiZWwxOTg2NDM0MTc5",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20tensorpipe",
          "name": "module: tensorpipe",
          "color": "f7e845",
          "default": false,
          "description": "Related to Tensorpipe RPC Agent"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 2,
      "created_at": "2020-06-03T18:10:22Z",
      "updated_at": "2020-06-03T18:49:22Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "\r\nhttps://app.circleci.com/pipelines/github/pytorch/pytorch/176463/workflows/013c36ff-c568-4726-a10f-fc6fc342ac0c/jobs/5670885/steps\r\n\r\n```\r\nJun 03 17:38:08   test_backward_node_failure (__main__.TensorPipeAgentDistAutogradTestWithSpawn) ... [W tensorpipe_agent.cpp:312] RPC agent for worker3 encountered error when reading incoming request: pipe closed\r\nJun 03 17:38:08 [E container.cpp:248] Could not release Dist Autograd Context on node 0: pipe closed\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:312] RPC agent for worker0 encountered error when reading incoming request: EOF: end of file\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:280] RPC agent for worker0 encountered error when writing outgoing response: EOF: end of file\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:436] RPC agent for worker0 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 03 17:38:08 [E container.cpp:248] Could not release Dist Autograd Context on node 2: pipe closed\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:312] RPC agent for worker1 encountered error when reading incoming request: pipe closed\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:312] RPC agent for worker2 encountered error when reading incoming request: EOF: end of file\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:436] RPC agent for worker2 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:280] RPC agent for worker2 encountered error when writing outgoing response: EOF: end of file\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:436] RPC agent for worker2 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:453] RPC agent for worker0 encountered error when reading incoming request: EOF: end of file\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:436] RPC agent for worker2 encountered error when writing outgoing request: EPIPE: broken pipe\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:436] RPC agent for worker2 encountered error when writing outgoing request: EPIPE: broken pipe\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:436] RPC agent for worker0 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:436] RPC agent for worker2 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:436] RPC agent for worker2 encountered error when writing outgoing request: EPIPE: broken pipe\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:436] RPC agent for worker0 encountered error when writing outgoing request: EOF: end of file\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:436] RPC agent for worker0 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 03 17:38:08 [W tensorpipe_agent.cpp:436] RPC agent for worker0 encountered error when writing outgoing request: EOF: end of file\r\nJun 03 17:39:47 Timing out after 100 seconds and killing subprocesses.\r\nJun 03 17:39:47 ERROR (100.070s)\r\n```\r\n\r\n```\r\nJun 03 17:43:08 ======================================================================\r\nJun 03 17:43:08 ERROR [100.070s]: test_backward_node_failure (__main__.TensorPipeAgentDistAutogradTestWithSpawn)\r\nJun 03 17:43:08 ----------------------------------------------------------------------\r\nJun 03 17:43:08 Traceback (most recent call last):\r\nJun 03 17:43:08   File \"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py\", line 204, in wrapper\r\nJun 03 17:43:08     self._join_processes(fn)\r\nJun 03 17:43:08   File \"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py\", line 306, in _join_processes\r\nJun 03 17:43:08     self._check_return_codes(elapsed_time)\r\nJun 03 17:43:08   File \"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py\", line 344, in _check_return_codes\r\nJun 03 17:43:08     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))\r\nJun 03 17:43:08 RuntimeError: Process 2 terminated or timed out after 100.05238389968872 seconds\r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/38835",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/38835/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/38835/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/38835/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/38835",
      "id": 622144777,
      "node_id": "MDU6SXNzdWU2MjIxNDQ3Nzc=",
      "number": 38835,
      "title": "DISABLED test_reduce_scatter (__main__.TestNCCL)",
      "user": {
        "login": "pritamdamania87",
        "id": 9958665,
        "node_id": "MDQ6VXNlcjk5NTg2NjU=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/9958665?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/pritamdamania87",
        "html_url": "https://github.com/pritamdamania87",
        "followers_url": "https://api.github.com/users/pritamdamania87/followers",
        "following_url": "https://api.github.com/users/pritamdamania87/following{/other_user}",
        "gists_url": "https://api.github.com/users/pritamdamania87/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/pritamdamania87/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pritamdamania87/subscriptions",
        "organizations_url": "https://api.github.com/users/pritamdamania87/orgs",
        "repos_url": "https://api.github.com/users/pritamdamania87/repos",
        "events_url": "https://api.github.com/users/pritamdamania87/events{/privacy}",
        "received_events_url": "https://api.github.com/users/pritamdamania87/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 2,
      "created_at": "2020-05-20T23:24:19Z",
      "updated_at": "2020-06-01T21:11:48Z",
      "closed_at": null,
      "author_association": "NONE",
      "body": "https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28226//console\r\nhttps://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28233//console\r\nhttps://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28234//console\r\n\r\n\n\ncc @ezyang @gchanan @zou3519",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/38722",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/38722/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/38722/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/38722/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/38722",
      "id": 621037319,
      "node_id": "MDU6SXNzdWU2MjEwMzczMTk=",
      "number": 38722,
      "title": "DISABLED test_remote_script_module (__main__.JitRpcTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953983,
          "node_id": "MDU6TGFiZWw2Nzk5NTM5ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/jit",
          "name": "jit",
          "color": "c5def5",
          "default": false,
          "description": null
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "pritamdamania87",
        "id": 9958665,
        "node_id": "MDQ6VXNlcjk5NTg2NjU=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/9958665?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/pritamdamania87",
        "html_url": "https://github.com/pritamdamania87",
        "followers_url": "https://api.github.com/users/pritamdamania87/followers",
        "following_url": "https://api.github.com/users/pritamdamania87/following{/other_user}",
        "gists_url": "https://api.github.com/users/pritamdamania87/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/pritamdamania87/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pritamdamania87/subscriptions",
        "organizations_url": "https://api.github.com/users/pritamdamania87/orgs",
        "repos_url": "https://api.github.com/users/pritamdamania87/repos",
        "events_url": "https://api.github.com/users/pritamdamania87/events{/privacy}",
        "received_events_url": "https://api.github.com/users/pritamdamania87/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "pritamdamania87",
          "id": 9958665,
          "node_id": "MDQ6VXNlcjk5NTg2NjU=",
          "avatar_url": "https://avatars1.githubusercontent.com/u/9958665?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/pritamdamania87",
          "html_url": "https://github.com/pritamdamania87",
          "followers_url": "https://api.github.com/users/pritamdamania87/followers",
          "following_url": "https://api.github.com/users/pritamdamania87/following{/other_user}",
          "gists_url": "https://api.github.com/users/pritamdamania87/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/pritamdamania87/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/pritamdamania87/subscriptions",
          "organizations_url": "https://api.github.com/users/pritamdamania87/orgs",
          "repos_url": "https://api.github.com/users/pritamdamania87/repos",
          "events_url": "https://api.github.com/users/pritamdamania87/events{/privacy}",
          "received_events_url": "https://api.github.com/users/pritamdamania87/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-05-19T14:45:19Z",
      "updated_at": "2020-06-01T20:09:20Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/171687/workflows/704f208c-d74a-4fa0-9579-334819e55a40/jobs/5520032/steps\r\n\r\n```\r\nMay 19 05:26:19 ======================================================================\r\nMay 19 05:26:19 ERROR [1.121s]: test_remote_script_module (__main__.JitRpcTestWithSpawn)\r\nMay 19 05:26:19 ----------------------------------------------------------------------\r\nMay 19 05:26:19 Traceback (most recent call last):\r\nMay 19 05:26:19   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 204, in wrapper\r\nMay 19 05:26:19     self._join_processes(fn)\r\nMay 19 05:26:19   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 306, in _join_processes\r\nMay 19 05:26:19     self._check_return_codes(elapsed_time)\r\nMay 19 05:26:19   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 339, in _check_return_codes\r\nMay 19 05:26:19     raise RuntimeError(error)\r\nMay 19 05:26:19 RuntimeError: Processes 2 exited with error code 10\r\n```\r\n\r\n```\r\nMay 19 05:25:59   test_remote_script_module (__main__.JitRpcTestWithSpawn) ... [E request_callback_impl.cpp:96] Received error while processing request type 0: \r\nMay 19 05:25:59 Unknown type name '__torch__.torch.testing._internal.distributed.rpc.jit.rpc_test.MyModuleInterface':\r\nMay 19 05:25:59 __torch__.torch.testing._internal.distributed.rpc.jit.rpc_test.MyModuleInterface\r\nMay 19 05:25:59 ERROR:root:Caught exception: \r\nMay 19 05:25:59 Traceback (most recent call last):\r\nMay 19 05:25:59   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 207, in wrapper\r\nMay 19 05:25:59     fn()\r\nMay 19 05:25:59   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py\", line 85, in new_test_method\r\nMay 19 05:25:59     return_value = old_test_method(self, *arg, **kwargs)\r\nMay 19 05:25:59   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py\", line 889, in test_remote_script_module\r\nMay 19 05:25:59     args=(remote_ref, torch.ones(self.rank)),\r\nMay 19 05:25:59   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 77, in wrapper\r\nMay 19 05:25:59     return func(*args, **kwargs)\r\nMay 19 05:25:59   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 614, in rpc_sync\r\nMay 19 05:25:59     return fut.wait()\r\nMay 19 05:25:59 RuntimeError: Error on Node 3: \r\nMay 19 05:25:59 Unknown type name '__torch__.torch.testing._internal.distributed.rpc.jit.rpc_test.MyModuleInterface':\r\nMay 19 05:25:59 __torch__.torch.testing._internal.distributed.rpc.jit.rpc_test.MyModuleInterface\r\nMay 19 05:25:59 exiting process with exit code: 10\r\nMay 19 05:25:59 [E request_callback_impl.cpp:96] Received error while processing request type 0: The following operation failed in the TorchScript interpreter.\r\nMay 19 05:25:59 Traceback of TorchScript (most recent call last):\r\nMay 19 05:25:59   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py\", line 799, in run_ref_script_module\r\nMay 19 05:25:59 def run_ref_script_module(ref_script_module, t):\r\nMay 19 05:25:59     # type: (RRef[MyModuleInterface], Tensor) -> Tensor\r\nMay 19 05:25:59     module = ref_script_module.to_here()\r\nMay 19 05:25:59              ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\r\nMay 19 05:25:59     return module.forward() + t\r\nMay 19 05:25:59 RuntimeError: User RRef with RRefId=GloballyUniqueId(1, 0) and ForkId=GloballyUniqueId(1, 3) is an RRef to a ScriptModule. It can't be sent through RPC from owner, worker2, to user, worker1.\r\nMay 19 05:25:59 \r\nMay 19 05:25:59 [E request_callback_impl.cpp:96] Received error while processing request type 0: The following operation failed in the TorchScript interpreter.\r\nMay 19 05:25:59 Traceback of TorchScript (most recent call last):\r\nMay 19 05:25:59   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py\", line 799, in run_ref_script_module\r\nMay 19 05:25:59 def run_ref_script_module(ref_script_module, t):\r\nMay 19 05:25:59     # type: (RRef[MyModuleInterface], Tensor) -> Tensor\r\nMay 19 05:25:59     module = ref_script_module.to_here()\r\nMay 19 05:25:59              ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\r\nMay 19 05:25:59     return module.forward() + t\r\nMay 19 05:25:59 RuntimeError: User RRef with RRefId=GloballyUniqueId(0, 0) and ForkId=GloballyUniqueId(0, 3) is an RRef to a ScriptModule. It can't be sent through RPC from owner, worker1, to user, worker0.\r\nMay 19 05:25:59 \r\nMay 19 05:25:59 [E request_callback_impl.cpp:96] Received error while processing request type 0: The following operation failed in the TorchScript interpreter.\r\nMay 19 05:25:59 Traceback of TorchScript (most recent call last):\r\nMay 19 05:25:59   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py\", line 799, in run_ref_script_module\r\nMay 19 05:25:59 def run_ref_script_module(ref_script_module, t):\r\nMay 19 05:25:59     # type: (RRef[MyModuleInterface], Tensor) -> Tensor\r\nMay 19 05:25:59     module = ref_script_module.to_here()\r\nMay 19 05:25:59              ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE\r\nMay 19 05:25:59     return module.forward() + t\r\nMay 19 05:25:59 RuntimeError: User RRef with RRefId=GloballyUniqueId(3, 0) and ForkId=GloballyUniqueId(3, 3) is an RRef to a ScriptModule. It can't be sent through RPC from owner, worker0, to user, worker3.\r\nMay 19 05:25:59 \r\nMay 19 05:25:59 Process 2 terminated with exit code 10, terminating remaining processes.\r\nMay 19 05:25:59 ERROR (1.121s)\r\nMay 19 05:26:00   test_remote_script_throw (__main__.JitRpcTestWithSpawn) ... [E request_callback_impl.cpp:96] Received error while processing request type 7: The following operation failed in the TorchScript interpreter.\r\nMay 19 05:26:00 Traceback of TorchScript (most recent call last):\r\nMay 19 05:26:00   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py\", line 136, in script_raise_func\r\nMay 19 05:26:00 def script_raise_func(value):\r\nMay 19 05:26:00     if value.numel() == 2:\r\nMay 19 05:26:00         raise ValueError(\"Expected error\")\r\nMay 19 05:26:00         ~~~~~~~~~~~~~~~~~~ <--- HERE\r\nMay 19 05:26:00     return value + 1\r\nMay 19 05:26:00 RuntimeError: Exception\r\n```\n\ncc @ezyang @gchanan @zou3519 @suo @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/39464",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/39464/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/39464/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/39464/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/39464",
      "id": 630255509,
      "node_id": "MDU6SXNzdWU2MzAyNTU1MDk=",
      "number": 39464,
      "title": "DISABLED test_backward_node_failure_python_udf (__main__.TensorPipeAgentDistAutogradTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1986434179,
          "node_id": "MDU6TGFiZWwxOTg2NDM0MTc5",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20tensorpipe",
          "name": "module: tensorpipe",
          "color": "f7e845",
          "default": false,
          "description": "Related to Tensorpipe RPC Agent"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 1,
      "created_at": "2020-06-03T19:14:47Z",
      "updated_at": "2020-06-03T19:15:02Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/176505/workflows/8f440b54-caea-453a-b9ad-3385827a6ea9/jobs/5672422/steps\r\n\r\n\r\n```\r\nJun 03 19:00:50   test_backward_node_failure_python_udf (__main__.TensorPipeAgentDistAutogradTestWithSpawn) ... [W tensorpipe_agent.cpp:312] RPC agent for worker2 encountered error when reading incoming request: pipe closed\r\nJun 03 19:00:50 [W tensorpipe_agent.cpp:312] RPC agent for worker2 encountered error when reading incoming request: pipe closed\r\nJun 03 19:00:50 [E container.cpp:248] Could not release Dist Autograd Context on node 3: pipe closed\r\nJun 03 19:00:50 terminate called after throwing an instance of 'std::out_of_range'\r\nJun 03 19:00:50   what():  _Map_base::at\r\n```\r\n\r\n\r\n```\r\nJun 03 19:04:08 ======================================================================\r\nJun 03 19:04:08 FAIL [1.620s]: test_backward_node_failure_python_udf (__main__.TensorPipeAgentDistAutogradTestWithSpawn)\r\nJun 03 19:04:08 ----------------------------------------------------------------------\r\nJun 03 19:04:08 Traceback (most recent call last):\r\nJun 03 19:04:08   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 204, in wrapper\r\nJun 03 19:04:08     self._join_processes(fn)\r\nJun 03 19:04:08   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 306, in _join_processes\r\nJun 03 19:04:08     self._check_return_codes(elapsed_time)\r\nJun 03 19:04:08   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 349, in _check_return_codes\r\nJun 03 19:04:08     i, first_process.exitcode, p.exitcode\r\nJun 03 19:04:08   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 1100, in assertEqual\r\nJun 03 19:04:08     self.assertTrue(result, msg=msg)\r\nJun 03 19:04:08 AssertionError: False is not true : Expect process 2 exit code to match Process 0 exit code of 0, but got -6\r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/39445",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/39445/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/39445/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/39445/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/39445",
      "id": 630008873,
      "node_id": "MDU6SXNzdWU2MzAwMDg4NzM=",
      "number": 39445,
      "title": "DISABLED test_graph_for_python_remote_call (__main__.DistAutogradTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-06-03T13:46:42Z",
      "updated_at": "2020-06-03T13:46:47Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/176130/workflows/56fefa1d-d892-4af3-9469-5eaaa22b1d0b/jobs/5658716/steps\r\n\r\nObserved on tests for commit 09bea1398141e0f74afb1e22d380d3322ba28105\r\n\r\n```\r\nJun 02 21:11:00   test_graph_for_python_remote_call (__main__.DistAutogradTestWithSpawn) ... Timing out after 100 seconds and killing subprocesses.\r\nJun 02 21:11:00 ERROR (100.099s)\r\n```\r\n\r\n\r\n```\r\nJun 02 21:11:25 ======================================================================\r\nJun 02 21:11:25 ERROR [100.099s]: test_graph_for_python_remote_call (__main__.DistAutogradTestWithSpawn)\r\nJun 02 21:11:25 ----------------------------------------------------------------------\r\nJun 02 21:11:25 Traceback (most recent call last):\r\nJun 02 21:11:25   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 204, in wrapper\r\nJun 02 21:11:25     self._join_processes(fn)\r\nJun 02 21:11:25   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 306, in _join_processes\r\nJun 02 21:11:25     self._check_return_codes(elapsed_time)\r\nJun 02 21:11:25   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 344, in _check_return_codes\r\nJun 02 21:11:25     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))\r\nJun 02 21:11:25 RuntimeError: Process 0 terminated or timed out after 100.07846069335938 seconds\r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/36332",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/36332/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/36332/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/36332/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/36332",
      "id": 597507619,
      "node_id": "MDU6SXNzdWU1OTc1MDc2MTk=",
      "number": 36332,
      "title": "DISABLED test_check_failed_messages (__main__.FaultyAgentRpcTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "osalpekar",
        "id": 14008860,
        "node_id": "MDQ6VXNlcjE0MDA4ODYw",
        "avatar_url": "https://avatars2.githubusercontent.com/u/14008860?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/osalpekar",
        "html_url": "https://github.com/osalpekar",
        "followers_url": "https://api.github.com/users/osalpekar/followers",
        "following_url": "https://api.github.com/users/osalpekar/following{/other_user}",
        "gists_url": "https://api.github.com/users/osalpekar/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/osalpekar/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/osalpekar/subscriptions",
        "organizations_url": "https://api.github.com/users/osalpekar/orgs",
        "repos_url": "https://api.github.com/users/osalpekar/repos",
        "events_url": "https://api.github.com/users/osalpekar/events{/privacy}",
        "received_events_url": "https://api.github.com/users/osalpekar/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "osalpekar",
          "id": 14008860,
          "node_id": "MDQ6VXNlcjE0MDA4ODYw",
          "avatar_url": "https://avatars2.githubusercontent.com/u/14008860?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/osalpekar",
          "html_url": "https://github.com/osalpekar",
          "followers_url": "https://api.github.com/users/osalpekar/followers",
          "following_url": "https://api.github.com/users/osalpekar/following{/other_user}",
          "gists_url": "https://api.github.com/users/osalpekar/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/osalpekar/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/osalpekar/subscriptions",
          "organizations_url": "https://api.github.com/users/osalpekar/orgs",
          "repos_url": "https://api.github.com/users/osalpekar/repos",
          "events_url": "https://api.github.com/users/osalpekar/events{/privacy}",
          "received_events_url": "https://api.github.com/users/osalpekar/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 2,
      "created_at": "2020-04-09T19:36:45Z",
      "updated_at": "2020-05-19T22:50:22Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/153028/workflows/c3ba2031-4e43-41d4-8399-c69cd09b49d7/jobs/5100538\r\n\r\n```\r\nApr 09 11:58:38 ======================================================================\r\nApr 09 11:58:38 ERROR [100.118s]: test_check_failed_messages (__main__.FaultyAgentRpcTestWithSpawn)\r\nApr 09 11:58:38 ----------------------------------------------------------------------\r\nApr 09 11:58:38 Traceback (most recent call last):\r\nApr 09 11:58:38   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 175, in wrapper\r\nApr 09 11:58:38     self._join_processes(fn)\r\nApr 09 11:58:38   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 285, in _join_processes\r\nApr 09 11:58:38     self._check_return_codes(elapsed_time)\r\nApr 09 11:58:38   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 323, in _check_return_codes\r\nApr 09 11:58:38     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))\r\nApr 09 11:58:38 RuntimeError: Process 1 terminated or timed out after 100.0106930732727 seconds\r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/35575",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/35575/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/35575/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/35575/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/35575",
      "id": 589428376,
      "node_id": "MDU6SXNzdWU1ODk0MjgzNzY=",
      "number": 35575,
      "title": "DISABLED test_debug_info (__main__.DistAutogradTestWithSpawn)",
      "user": {
        "login": "xush6528",
        "id": 7608630,
        "node_id": "MDQ6VXNlcjc2MDg2MzA=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/7608630?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/xush6528",
        "html_url": "https://github.com/xush6528",
        "followers_url": "https://api.github.com/users/xush6528/followers",
        "following_url": "https://api.github.com/users/xush6528/following{/other_user}",
        "gists_url": "https://api.github.com/users/xush6528/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/xush6528/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/xush6528/subscriptions",
        "organizations_url": "https://api.github.com/users/xush6528/orgs",
        "repos_url": "https://api.github.com/users/xush6528/repos",
        "events_url": "https://api.github.com/users/xush6528/events{/privacy}",
        "received_events_url": "https://api.github.com/users/xush6528/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 2,
      "created_at": "2020-03-27T21:44:25Z",
      "updated_at": "2020-05-11T01:38:23Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "Saw 2 instances on test, pytorch_linux_xenial_py3_6_gcc5_4_test\r\n\r\nhttps://app.circleci.com/pipelines/github/pytorch/pytorch/147576/workflows/ee6a83a9-b219-488c-8224-b1d8404ad9f1/jobs/4978490\r\n\r\nhttps://app.circleci.com/pipelines/github/pytorch/pytorch/147327/workflows/b0fd43f7-d18a-4b47-a6c2-8c881c1cac63/jobs/4972041\n\ncc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/37495",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/37495/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/37495/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/37495/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/37495",
      "id": 608912043,
      "node_id": "MDU6SXNzdWU2MDg5MTIwNDM=",
      "number": 37495,
      "title": "DISABLED test_default_quantized_lstm (quantization.test_quantize.TestPostTrainingDynamic)",
      "user": {
        "login": "mruberry",
        "id": 38511765,
        "node_id": "MDQ6VXNlcjM4NTExNzY1",
        "avatar_url": "https://avatars3.githubusercontent.com/u/38511765?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mruberry",
        "html_url": "https://github.com/mruberry",
        "followers_url": "https://api.github.com/users/mruberry/followers",
        "following_url": "https://api.github.com/users/mruberry/following{/other_user}",
        "gists_url": "https://api.github.com/users/mruberry/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mruberry/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mruberry/subscriptions",
        "organizations_url": "https://api.github.com/users/mruberry/orgs",
        "repos_url": "https://api.github.com/users/mruberry/repos",
        "events_url": "https://api.github.com/users/mruberry/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mruberry/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1031340614,
          "node_id": "MDU6TGFiZWwxMDMxMzQwNjE0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/quantization",
          "name": "quantization",
          "color": "f7e101",
          "default": false,
          "description": "Quantization support in PyTorch"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "raghuramank100",
        "id": 48835916,
        "node_id": "MDQ6VXNlcjQ4ODM1OTE2",
        "avatar_url": "https://avatars1.githubusercontent.com/u/48835916?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/raghuramank100",
        "html_url": "https://github.com/raghuramank100",
        "followers_url": "https://api.github.com/users/raghuramank100/followers",
        "following_url": "https://api.github.com/users/raghuramank100/following{/other_user}",
        "gists_url": "https://api.github.com/users/raghuramank100/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/raghuramank100/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/raghuramank100/subscriptions",
        "organizations_url": "https://api.github.com/users/raghuramank100/orgs",
        "repos_url": "https://api.github.com/users/raghuramank100/repos",
        "events_url": "https://api.github.com/users/raghuramank100/events{/privacy}",
        "received_events_url": "https://api.github.com/users/raghuramank100/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "raghuramank100",
          "id": 48835916,
          "node_id": "MDQ6VXNlcjQ4ODM1OTE2",
          "avatar_url": "https://avatars1.githubusercontent.com/u/48835916?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/raghuramank100",
          "html_url": "https://github.com/raghuramank100",
          "followers_url": "https://api.github.com/users/raghuramank100/followers",
          "following_url": "https://api.github.com/users/raghuramank100/following{/other_user}",
          "gists_url": "https://api.github.com/users/raghuramank100/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/raghuramank100/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/raghuramank100/subscriptions",
          "organizations_url": "https://api.github.com/users/raghuramank100/orgs",
          "repos_url": "https://api.github.com/users/raghuramank100/repos",
          "events_url": "https://api.github.com/users/raghuramank100/events{/privacy}",
          "received_events_url": "https://api.github.com/users/raghuramank100/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 1,
      "created_at": "2020-04-29T09:33:17Z",
      "updated_at": "2020-05-12T03:55:54Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "This test is failing intermittently on multiple builds with increasing frequency recently and no clear cause. \r\n\r\n```\r\nApr 29 09:14:17 ======================================================================\r\nApr 29 09:14:17 ERROR [0.030s]: test_default_quantized_lstm (quantization.test_quantize.TestPostTrainingDynamic)\r\nApr 29 09:14:17 ----------------------------------------------------------------------\r\nApr 29 09:14:17 Traceback (most recent call last):\r\nApr 29 09:14:17   File \"/var/lib/jenkins/workspace/test/quantization/test_quantize.py\", line 862, in test_default_quantized_lstm\r\nApr 29 09:14:17     y, (h, c) = cell_dq(x, (h, c))\r\nApr 29 09:14:17   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 562, in __call__\r\nApr 29 09:14:17     result = self.forward(*input, **kwargs)\r\nApr 29 09:14:17   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 351, in forward\r\nApr 29 09:14:17     return self.forward_tensor(input, hx)\r\nApr 29 09:14:17   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 312, in forward_tensor\r\nApr 29 09:14:17     input, hx, batch_sizes, max_batch_size, sorted_indices)\r\nApr 29 09:14:17   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 293, in forward_impl\r\nApr 29 09:14:17     self.batch_first, dtype=self.dtype, use_dynamic=True)\r\nApr 29 09:14:17 RuntimeError: In ChooseQuantizationParams, min should be less than or equal to max\r\n```\r\n\n\ncc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/35761",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/35761/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/35761/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/35761/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/35761",
      "id": 591252770,
      "node_id": "MDU6SXNzdWU1OTEyNTI3NzA=",
      "number": 35761,
      "title": "Allow shuffle when auto-batching disabled in `DataLoader`",
      "user": {
        "login": "huww98",
        "id": 15710934,
        "node_id": "MDQ6VXNlcjE1NzEwOTM0",
        "avatar_url": "https://avatars2.githubusercontent.com/u/15710934?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/huww98",
        "html_url": "https://github.com/huww98",
        "followers_url": "https://api.github.com/users/huww98/followers",
        "following_url": "https://api.github.com/users/huww98/following{/other_user}",
        "gists_url": "https://api.github.com/users/huww98/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/huww98/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/huww98/subscriptions",
        "organizations_url": "https://api.github.com/users/huww98/orgs",
        "repos_url": "https://api.github.com/users/huww98/repos",
        "events_url": "https://api.github.com/users/huww98/events{/privacy}",
        "received_events_url": "https://api.github.com/users/huww98/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1301447942,
          "node_id": "MDU6TGFiZWwxMzAxNDQ3OTQy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/enhancement",
          "name": "enhancement",
          "color": "ffc6f4",
          "default": true,
          "description": "Not as big of a feature, but technically not a bug. Should be easy to fix"
        },
        {
          "id": 1076923878,
          "node_id": "MDU6TGFiZWwxMDc2OTIzODc4",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20dataloader",
          "name": "module: dataloader",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.utils.data.DataLoader and Sampler"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 1,
      "created_at": "2020-03-31T16:37:09Z",
      "updated_at": "2020-06-03T19:53:32Z",
      "closed_at": null,
      "author_association": "NONE",
      "body": "## 🚀 Feature\r\nAllow `DataLoader(batch_size=None, shuffle=True)`\r\n\r\n## Motivation\r\n\r\n<!-- Please outline the motivation for the proposal. Is your feature request related to a problem? e.g., I'm always frustrated when [...]. If this is related to another GitHub issue, please link here too -->\r\nMy model handles one sample a time. So, I don't need auto-batching, but I want my dataset to be shuffled. However, when I use `DataLoader(batch_size=None, shuffle=True)`, it raises `batch_size=None option disables auto-batching and is mutually exclusive with shuffle, and drop_last`.\r\n\r\nBut I can't see why they are mutually exclusive.\r\n\r\n## Pitch\r\n\r\n<!-- A clear and concise description of what you want to happen. -->\r\nAllow `DataLoader(batch_size=None, shuffle=True)`.\r\n\r\nBasically, just remove the `shuffle` check from this line:  https://github.com/pytorch/pytorch/blob/ada647214f3c39b3fdf624dd62f8295c92144617/torch/utils/data/dataloader.py#L202\r\n\r\n## Alternatives\r\n\r\n<!-- A clear and concise description of any alternative solutions or features you've considered, if any. -->\r\nI can:\r\n* Use `batch_size=1` then remove the batching dimension afterwards\r\n* Use `sampler=RandomSampler(dataset)`\r\n\r\nBut these makes me feel like I'm fighting with DataLoader. Why I cannot just use `shuffle=True`?\r\n\r\n## Additional context\r\n\r\n<!-- Add any other context or screenshots about the feature request here. -->\r\n\n\ncc @SsnL",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/37409",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/37409/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/37409/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/37409/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/37409",
      "id": 608167791,
      "node_id": "MDU6SXNzdWU2MDgxNjc3OTE=",
      "number": 37409,
      "title": "Compatibility of subset dataset with disabled batch sampling",
      "user": {
        "login": "dvirginz",
        "id": 31047807,
        "node_id": "MDQ6VXNlcjMxMDQ3ODA3",
        "avatar_url": "https://avatars2.githubusercontent.com/u/31047807?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dvirginz",
        "html_url": "https://github.com/dvirginz",
        "followers_url": "https://api.github.com/users/dvirginz/followers",
        "following_url": "https://api.github.com/users/dvirginz/following{/other_user}",
        "gists_url": "https://api.github.com/users/dvirginz/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dvirginz/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dvirginz/subscriptions",
        "organizations_url": "https://api.github.com/users/dvirginz/orgs",
        "repos_url": "https://api.github.com/users/dvirginz/repos",
        "events_url": "https://api.github.com/users/dvirginz/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dvirginz/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1076923878,
          "node_id": "MDU6TGFiZWwxMDc2OTIzODc4",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20dataloader",
          "name": "module: dataloader",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.utils.data.DataLoader and Sampler"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 3,
      "created_at": "2020-04-28T09:32:27Z",
      "updated_at": "2020-04-29T07:52:13Z",
      "closed_at": null,
      "author_association": "NONE",
      "body": "I think there is a compatibility issue with disabled batch sampling and subset dataset\r\nThe use-case - define custom batch sampling, and split the dataset using PyTorch split utility function\r\nHere's a minimal working example\r\n```\r\nself.train_dataset, self.val_dataset, self.test_dataset = torch.utils.data.random_split(\r\n            self.dataset, [100, 100, 100])\r\n\r\nloader = DataLoader(\r\n                dataset=self.train_dataset,\r\n                batch_size=None,\r\n                batch_sampler=None,\r\n                sampler=BatchSampler(\r\n                    SequentialSampler(dataset), batch_size=self.hparams.batch_size, drop_last=False),\r\n                num_workers=self.hparams.num_data_workers,\r\n            )\r\n```\r\nAnd when iterating the subset datasets this is the error\r\n```\r\nException has occurred: TypeError\r\nlist indices must be integers or slices, not list\r\n  File \"/path/utils/data/dataset.py\", line 257, in __getitem__\r\n    return self.dataset[self.indices[idx]]\r\n  File \"/path/utils/data/_utils/fetch.py\", line 46, in fetch\r\n    data = self.dataset[possibly_batched_index]\r\n  File \"/path/utils/data/dataloader.py\", line 385, in _next_data\r\n    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration\r\n  File \"/path/utils/data/dataloader.py\", line 345, in __next__\r\n    data = self._next_data()\r\n  File \"/path/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py\", line 251, in _evaluate\r\n    for batch_idx, batch in enumerate(dataloader):\r\n  File \"/path/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py\", line 843, in run_pretrain_routine\r\n    False)\r\n  File \"/path/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py\", line 477, in single_gpu_train\r\n    self.run_pretrain_routine(model)\r\n  File \"/path/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py\", line 704, in fit\r\n    self.single_gpu_train(model)\r\n  File \"/path/train.py\", line 152, in main_train\r\n    trainer.fit(model)\r\n  File \"/path/train.py\", line 66, in main\r\n    main_train(model_class_pointer, hyperparams, logger)\r\n  File \"/path/train.py\", line 161, in <module>\r\n    main()\r\n  File \"/path/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/path/lib/python3.7/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/path/lib/python3.7/runpy.py\", line 263, in run_path\r\n    pkg_name=pkg_name, script_name=fname)\r\n  File \"/path/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/path/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\r\n    \"__main__\", mod_spec)\r\n```\r\n\r\nAs the self.indices of the `subset` object is a simple python list.\r\n\r\nPlease refer to the forum post, where @ptrblck  approves reproducing the bug and offering a workaround.\n\ncc @SsnL",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34658",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34658/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34658/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34658/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34658",
      "id": 580112392,
      "node_id": "MDU6SXNzdWU1ODAxMTIzOTI=",
      "number": 34658,
      "title": "DISABLED test_keypoint_rcnn (__main__.TestONNXRuntime_opset11)",
      "user": {
        "login": "eellison",
        "id": 11477974,
        "node_id": "MDQ6VXNlcjExNDc3OTc0",
        "avatar_url": "https://avatars2.githubusercontent.com/u/11477974?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/eellison",
        "html_url": "https://github.com/eellison",
        "followers_url": "https://api.github.com/users/eellison/followers",
        "following_url": "https://api.github.com/users/eellison/following{/other_user}",
        "gists_url": "https://api.github.com/users/eellison/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/eellison/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/eellison/subscriptions",
        "organizations_url": "https://api.github.com/users/eellison/orgs",
        "repos_url": "https://api.github.com/users/eellison/repos",
        "events_url": "https://api.github.com/users/eellison/events{/privacy}",
        "received_events_url": "https://api.github.com/users/eellison/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 693805995,
          "node_id": "MDU6TGFiZWw2OTM4MDU5OTU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20onnx",
          "name": "module: onnx",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.onnx"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 5,
      "created_at": "2020-03-12T17:48:30Z",
      "updated_at": "2020-03-13T17:59:05Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "## 🐛 Bug\r\n\r\nhttps://app.circleci.com/pipelines/github/pytorch/pytorch/138566/workflows/850299ec-3258-4e78-b680-cfad253c746a/jobs/4782754/parallel-runs/0/steps/0-105\r\n\r\n```\r\nMar 12 17:35:27 =================================== FAILURES ===================================\r\nMar 12 17:35:27 __________________ TestONNXRuntime_opset11.test_keypoint_rcnn __________________\r\nMar 12 17:35:27 \r\nMar 12 17:35:27 self = <test_pytorch_onnx_onnxruntime.TestONNXRuntime_opset11 testMethod=test_keypoint_rcnn>\r\nMar 12 17:35:27 \r\nMar 12 17:35:27     def wrapper(self):\r\nMar 12 17:35:27         if self.opset_version < min_opset_version:\r\nMar 12 17:35:27             raise unittest.SkipTest(\"Skip verify test for unsupported opset_version\")\r\nMar 12 17:35:27 >       return func(self)\r\nMar 12 17:35:27 \r\nMar 12 17:35:27 test/onnx/test_pytorch_common.py:54: \r\n```\r\n\n\ncc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/32644",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/32644/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/32644/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/32644/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/32644",
      "id": 555422490,
      "node_id": "MDU6SXNzdWU1NTU0MjI0OTA=",
      "number": 32644,
      "title": "DISABLED test_quantized_rnn (test_quanization.PostTrainingDynamicQuantTest)",
      "user": {
        "login": "rohan-varma",
        "id": 8039770,
        "node_id": "MDQ6VXNlcjgwMzk3NzA=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/8039770?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rohan-varma",
        "html_url": "https://github.com/rohan-varma",
        "followers_url": "https://api.github.com/users/rohan-varma/followers",
        "following_url": "https://api.github.com/users/rohan-varma/following{/other_user}",
        "gists_url": "https://api.github.com/users/rohan-varma/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rohan-varma/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rohan-varma/subscriptions",
        "organizations_url": "https://api.github.com/users/rohan-varma/orgs",
        "repos_url": "https://api.github.com/users/rohan-varma/repos",
        "events_url": "https://api.github.com/users/rohan-varma/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rohan-varma/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1031340614,
          "node_id": "MDU6TGFiZWwxMDMxMzQwNjE0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/quantization",
          "name": "quantization",
          "color": "f7e101",
          "default": false,
          "description": "Quantization support in PyTorch"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "z-a-f",
        "id": 4216323,
        "node_id": "MDQ6VXNlcjQyMTYzMjM=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/4216323?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/z-a-f",
        "html_url": "https://github.com/z-a-f",
        "followers_url": "https://api.github.com/users/z-a-f/followers",
        "following_url": "https://api.github.com/users/z-a-f/following{/other_user}",
        "gists_url": "https://api.github.com/users/z-a-f/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/z-a-f/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/z-a-f/subscriptions",
        "organizations_url": "https://api.github.com/users/z-a-f/orgs",
        "repos_url": "https://api.github.com/users/z-a-f/repos",
        "events_url": "https://api.github.com/users/z-a-f/events{/privacy}",
        "received_events_url": "https://api.github.com/users/z-a-f/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "z-a-f",
          "id": 4216323,
          "node_id": "MDQ6VXNlcjQyMTYzMjM=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/4216323?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/z-a-f",
          "html_url": "https://github.com/z-a-f",
          "followers_url": "https://api.github.com/users/z-a-f/followers",
          "following_url": "https://api.github.com/users/z-a-f/following{/other_user}",
          "gists_url": "https://api.github.com/users/z-a-f/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/z-a-f/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/z-a-f/subscriptions",
          "organizations_url": "https://api.github.com/users/z-a-f/orgs",
          "repos_url": "https://api.github.com/users/z-a-f/repos",
          "events_url": "https://api.github.com/users/z-a-f/events{/privacy}",
          "received_events_url": "https://api.github.com/users/z-a-f/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 15,
      "created_at": "2020-01-27T08:22:49Z",
      "updated_at": "2020-03-06T03:05:33Z",
      "closed_at": null,
      "author_association": "MEMBER",
      "body": "## 🐛 Bug\r\n\r\ntes_quantized_rnn is flaky, see https://app.circleci.com/jobs/github/pytorch/pytorch/4343194\r\nSee example failure: \r\n```\r\nJan 26 08:10:23 ======================================================================\r\nJan 26 08:10:23 ERROR [0.186s]: test_quantized_rnn (__main__.PostTrainingDynamicQuantTest)\r\nJan 26 08:10:23 ----------------------------------------------------------------------\r\nJan 26 08:10:23 Traceback (most recent call last):\r\nJan 26 08:10:23   File \"test_quantization.py\", line 722, in test_quantized_rnn\r\nJan 26 08:10:23     y, (h, c) = cell_dq(x, (h, c))\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 540, in __call__\r\nJan 26 08:10:23     result = self.forward(*input, **kwargs)\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 373, in forward\r\nJan 26 08:10:23     return self.forward_tensor(input, hx)\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 334, in forward_tensor\r\nJan 26 08:10:23     input, hx, batch_sizes, max_batch_size, sorted_indices)\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 315, in forward_impl\r\nJan 26 08:10:23     self.batch_first, dtype=self.dtype, use_dynamic=True)\r\nJan 26 08:10:23 RuntimeError: quantization scale should be > 0\r\n```\n\ncc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34213",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34213/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34213/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34213/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34213",
      "id": 575502768,
      "node_id": "MDU6SXNzdWU1NzU1MDI3Njg=",
      "number": 34213,
      "title": "DISABLED test_script_pack_padded_sequence (test_jit.TestScript)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953983,
          "node_id": "MDU6TGFiZWw2Nzk5NTM5ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/jit",
          "name": "jit",
          "color": "c5def5",
          "default": false,
          "description": null
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-03-04T15:29:15Z",
      "updated_at": "2020-03-09T17:09:59Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "Previous failed runs:\r\nhttps://circleci.com/gh/pytorch/pytorch/4682966\r\n\r\nSubsequent succeeded runs:\r\nhttps://circleci.com/gh/pytorch/pytorch/4682247\r\nhttps://circleci.com/gh/pytorch/pytorch/4682241\r\n\r\nToday, it consistently fails:\r\nhttps://circleci.com/gh/pytorch/pytorch/4687625\r\nhttps://circleci.com/gh/pytorch/pytorch/4687610\r\nhttps://circleci.com/gh/pytorch/pytorch/4686149\r\n\r\n@ljk53 tried reverting the seemingly culprit PR #32814 and #34055, but the error persist. \r\n\r\nI am going to disable this test while JIT team investigating it. \n\ncc @ezyang @gchanan @zou3519 @suo",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34432",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34432/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34432/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34432/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34432",
      "id": 577434425,
      "node_id": "MDU6SXNzdWU1Nzc0MzQ0MjU=",
      "number": 34432,
      "title": "DISABLED test_gloo_backend_1gpu_module_device_ids_integer_list (__main__.DistributedDataParallelTest)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953883,
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20distributed",
          "name": "module: distributed",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.distributed"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "pritamdamania87",
        "id": 9958665,
        "node_id": "MDQ6VXNlcjk5NTg2NjU=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/9958665?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/pritamdamania87",
        "html_url": "https://github.com/pritamdamania87",
        "followers_url": "https://api.github.com/users/pritamdamania87/followers",
        "following_url": "https://api.github.com/users/pritamdamania87/following{/other_user}",
        "gists_url": "https://api.github.com/users/pritamdamania87/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/pritamdamania87/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pritamdamania87/subscriptions",
        "organizations_url": "https://api.github.com/users/pritamdamania87/orgs",
        "repos_url": "https://api.github.com/users/pritamdamania87/repos",
        "events_url": "https://api.github.com/users/pritamdamania87/events{/privacy}",
        "received_events_url": "https://api.github.com/users/pritamdamania87/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "pritamdamania87",
          "id": 9958665,
          "node_id": "MDQ6VXNlcjk5NTg2NjU=",
          "avatar_url": "https://avatars1.githubusercontent.com/u/9958665?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/pritamdamania87",
          "html_url": "https://github.com/pritamdamania87",
          "followers_url": "https://api.github.com/users/pritamdamania87/followers",
          "following_url": "https://api.github.com/users/pritamdamania87/following{/other_user}",
          "gists_url": "https://api.github.com/users/pritamdamania87/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/pritamdamania87/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/pritamdamania87/subscriptions",
          "organizations_url": "https://api.github.com/users/pritamdamania87/orgs",
          "repos_url": "https://api.github.com/users/pritamdamania87/repos",
          "events_url": "https://api.github.com/users/pritamdamania87/events{/privacy}",
          "received_events_url": "https://api.github.com/users/pritamdamania87/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-03-08T02:42:25Z",
      "updated_at": "2020-05-06T21:19:46Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/20231//console\r\n\r\n```\r\n22:09:03 ======================================================================\r\n22:09:03 FAIL: test_gloo_backend_1gpu_module_device_ids_integer_list (__main__.DistributedDataParallelTest)\r\n22:09:03 ----------------------------------------------------------------------\r\n22:09:03 Traceback (most recent call last):\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 175, in wrapper\r\n22:09:03     self._join_processes(fn)\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 256, in _join_processes\r\n22:09:03     self._check_return_codes(elapsed_time)\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 276, in _check_return_codes\r\n22:09:03     self.assertEqual(p.exitcode, first_process.exitcode)\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 915, in assertEqual\r\n22:09:03     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)\r\n22:09:03 AssertionError: 16 not less than or equal to 1e-05 : \r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/31750",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/31750/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/31750/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/31750/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/31750",
      "id": 544251558,
      "node_id": "MDU6SXNzdWU1NDQyNTE1NTg=",
      "number": 31750,
      "title": "DISABLED test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset10::test_interpolate_downsample",
      "user": {
        "login": "Krovatkin",
        "id": 5086322,
        "node_id": "MDQ6VXNlcjUwODYzMjI=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/5086322?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Krovatkin",
        "html_url": "https://github.com/Krovatkin",
        "followers_url": "https://api.github.com/users/Krovatkin/followers",
        "following_url": "https://api.github.com/users/Krovatkin/following{/other_user}",
        "gists_url": "https://api.github.com/users/Krovatkin/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Krovatkin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Krovatkin/subscriptions",
        "organizations_url": "https://api.github.com/users/Krovatkin/orgs",
        "repos_url": "https://api.github.com/users/Krovatkin/repos",
        "events_url": "https://api.github.com/users/Krovatkin/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Krovatkin/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1679533716,
          "node_id": "MDU6TGFiZWwxNjc5NTMzNzE2",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/skipped",
          "name": "skipped",
          "color": "bfdadc",
          "default": false,
          "description": "Denotes a (flaky) test currently skipped in CI."
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 2,
      "created_at": "2019-12-31T19:03:16Z",
      "updated_at": "2020-01-02T14:49:19Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "Temporarily disabling a flakey test.",
      "score": 0.0
    }
  ]
}
