{
  "total_count": 9,
  "incomplete_results": false,
  "items": [
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34960",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34960/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34960/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34960/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34960",
      "id": 583863762,
      "node_id": "MDU6SXNzdWU1ODM4NjM3NjI=",
      "number": 34960,
      "title": "DISABLED test_autograd_context (__main__.DistAutogradTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "mrshenli",
          "id": 16999635,
          "node_id": "MDQ6VXNlcjE2OTk5NjM1",
          "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/mrshenli",
          "html_url": "https://github.com/mrshenli",
          "followers_url": "https://api.github.com/users/mrshenli/followers",
          "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
          "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
          "organizations_url": "https://api.github.com/users/mrshenli/orgs",
          "repos_url": "https://api.github.com/users/mrshenli/repos",
          "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
          "received_events_url": "https://api.github.com/users/mrshenli/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 2,
      "created_at": "2020-03-18T16:45:38Z",
      "updated_at": "2020-03-19T15:29:55Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/141487/workflows/6ccb9e3c-5ce3-4884-8c80-657207053845/jobs/4855438\r\n\r\n```\r\nMar 18 08:54:22 Generating XML reports...\r\nMar 18 08:54:23 Running distributed/rpc/test_dist_autograd_spawn ... [2020-03-18 08:54:23.107885]\r\nMar 18 08:54:24 \r\nMar 18 08:54:24 Running tests...\r\nMar 18 08:54:24 ----------------------------------------------------------------------\r\nMar 18 08:56:06 .Timing out after 100 seconds and killing subprocesses.\r\nMar 18 08:56:54 E..........ss....................Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 08:56:54 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 08:56:54 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 08:56:54 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 08:56:55 .[E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at ../aten/src/TH/generic/THTensorMath.cpp:41\r\nMar 18 08:56:55 [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at ../aten/src/TH/generic/THTensorMath.cpp:41\r\nMar 18 08:56:55 [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at ../aten/src/TH/generic/THTensorMath.cpp:41\r\nMar 18 08:56:55 [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at ../aten/src/TH/generic/THTensorMath.cpp:41\r\nMar 18 08:56:57 ./Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 08:56:57   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 08:56:57 /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 08:56:57   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 08:56:57 /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 08:56:57   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 08:56:57 /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 08:56:57   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 08:56:57 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 08:56:57 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (Warning: operator()Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. at  (../torch/csrc/jit/python/pybind_utils.h:operator() at 684../torch/csrc/jit/python/pybind_utils.h)\r\nMar 18 08:56:57 :684)\r\nMar 18 08:56:57 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 08:57:21 ................./Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 08:57:21   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 08:57:21 /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 08:57:21   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 08:57:21 /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 08:57:21   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 08:57:21 /Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 08:57:21   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 08:57:21 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 08:57:21 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 08:57:21 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 08:57:21 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at ../torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 08:57:31 ........\r\nMar 18 08:57:31 ======================================================================\r\nMar 18 08:57:31 ERROR [100.051s]: test_autograd_context (__main__.DistAutogradTestWithSpawn)\r\nMar 18 08:57:31 ----------------------------------------------------------------------\r\nMar 18 08:57:31 Traceback (most recent call last):\r\nMar 18 08:57:31   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 175, in wrapper\r\nMar 18 08:57:31     self._join_processes(fn)\r\nMar 18 08:57:31   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 285, in _join_processes\r\nMar 18 08:57:31     self._check_return_codes(elapsed_time)\r\nMar 18 08:57:31   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 323, in _check_return_codes\r\nMar 18 08:57:31     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))\r\nMar 18 08:57:31 RuntimeError: Process 0 terminated or timed out after 100.02388215065002 seconds\r\nMar 18 08:57:31 \r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34952",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34952/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34952/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34952/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34952",
      "id": 583722672,
      "node_id": "MDU6SXNzdWU1ODM3MjI2NzI=",
      "number": 34952,
      "title": "DISABLED test_backward_node_failure (__main__.DistAutogradTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "rohan-varma",
        "id": 8039770,
        "node_id": "MDQ6VXNlcjgwMzk3NzA=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/8039770?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rohan-varma",
        "html_url": "https://github.com/rohan-varma",
        "followers_url": "https://api.github.com/users/rohan-varma/followers",
        "following_url": "https://api.github.com/users/rohan-varma/following{/other_user}",
        "gists_url": "https://api.github.com/users/rohan-varma/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rohan-varma/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rohan-varma/subscriptions",
        "organizations_url": "https://api.github.com/users/rohan-varma/orgs",
        "repos_url": "https://api.github.com/users/rohan-varma/repos",
        "events_url": "https://api.github.com/users/rohan-varma/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rohan-varma/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "rohan-varma",
          "id": 8039770,
          "node_id": "MDQ6VXNlcjgwMzk3NzA=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/8039770?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/rohan-varma",
          "html_url": "https://github.com/rohan-varma",
          "followers_url": "https://api.github.com/users/rohan-varma/followers",
          "following_url": "https://api.github.com/users/rohan-varma/following{/other_user}",
          "gists_url": "https://api.github.com/users/rohan-varma/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/rohan-varma/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/rohan-varma/subscriptions",
          "organizations_url": "https://api.github.com/users/rohan-varma/orgs",
          "repos_url": "https://api.github.com/users/rohan-varma/repos",
          "events_url": "https://api.github.com/users/rohan-varma/events{/privacy}",
          "received_events_url": "https://api.github.com/users/rohan-varma/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 1,
      "created_at": "2020-03-18T13:19:48Z",
      "updated_at": "2020-03-18T16:11:46Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/141441/workflows/a4d5bdb8-6425-4c59-9997-a468ad951b01/jobs/4854537\r\n\r\n```\r\nMar 18 11:19:47 ----------------------------------------------------------------------\r\nMar 18 11:20:06 ............[E request_callback_impl.cpp:94] Received error while processing request type 15: TypeError: 'NoneType' object is not callable\r\nMar 18 11:20:48 F.....................Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 11:20:48 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 11:20:48 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 11:20:48 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 11:20:49 .[E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41\r\nMar 18 11:20:49 [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41\r\nMar 18 11:20:49 [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41\r\nMar 18 11:20:49 [E request_callback_impl.cpp:94] Received error while processing request type 15: size mismatch, m1: [3 x 3], m2: [6 x 6] at /var/lib/jenkins/workspace/aten/src/TH/generic/THTensorMath.cpp:41\r\nMar 18 11:20:50 .Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 11:20:50 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 11:20:50 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 11:20:50 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 11:20:50 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 11:20:50   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 11:20:50 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 11:20:50   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 11:20:50 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 11:20:50   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 11:20:50 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 11:20:50   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 11:21:14 .................Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 11:21:14 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 11:21:14 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 11:21:14 Warning: Using sparse tensors in TorchScript is experimental. Many optimization pathways have not been thoroughly tested with sparse tensors. Please include the fact that the network is running sparse tensors in any bug reports submitted. (operator() at /var/lib/jenkins/workspace/torch/csrc/jit/python/pybind_utils.h:684)\r\nMar 18 11:21:14 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 11:21:14   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 11:21:14 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 11:21:14   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 11:21:14 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 11:21:14   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 11:21:14 /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:1816: UserWarning: Argument order of nn.functional.embedding_bag was changed. Usage `embedding_bag(weight, input, ...)` is deprecated, and should now be `embedding_bag(input, weight, ...)`.\r\nMar 18 11:21:14   warnings.warn(\"Argument order of nn.functional.embedding_bag was changed. \"\r\nMar 18 11:21:23 ........\r\nMar 18 11:21:23 ======================================================================\r\nMar 18 11:21:23 FAIL [6.131s]: test_backward_node_failure (__main__.DistAutogradTestWithSpawn)\r\nMar 18 11:21:23 ----------------------------------------------------------------------\r\nMar 18 11:21:23 Traceback (most recent call last):\r\nMar 18 11:21:23   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 175, in wrapper\r\nMar 18 11:21:23     self._join_processes(fn)\r\nMar 18 11:21:23   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 285, in _join_processes\r\nMar 18 11:21:23     self._check_return_codes(elapsed_time)\r\nMar 18 11:21:23   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 324, in _check_return_codes\r\nMar 18 11:21:23     self.assertEqual(p.exitcode, first_process.exitcode)\r\nMar 18 11:21:23   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 915, in assertEqual\r\nMar 18 11:21:23     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)\r\nMar 18 11:21:23 AssertionError: 11 not less than or equal to 1e-05 : \r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34658",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34658/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34658/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34658/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34658",
      "id": 580112392,
      "node_id": "MDU6SXNzdWU1ODAxMTIzOTI=",
      "number": 34658,
      "title": "DISABLED test_keypoint_rcnn (__main__.TestONNXRuntime_opset11)",
      "user": {
        "login": "eellison",
        "id": 11477974,
        "node_id": "MDQ6VXNlcjExNDc3OTc0",
        "avatar_url": "https://avatars2.githubusercontent.com/u/11477974?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/eellison",
        "html_url": "https://github.com/eellison",
        "followers_url": "https://api.github.com/users/eellison/followers",
        "following_url": "https://api.github.com/users/eellison/following{/other_user}",
        "gists_url": "https://api.github.com/users/eellison/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/eellison/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/eellison/subscriptions",
        "organizations_url": "https://api.github.com/users/eellison/orgs",
        "repos_url": "https://api.github.com/users/eellison/repos",
        "events_url": "https://api.github.com/users/eellison/events{/privacy}",
        "received_events_url": "https://api.github.com/users/eellison/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 693805995,
          "node_id": "MDU6TGFiZWw2OTM4MDU5OTU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20onnx",
          "name": "module: onnx",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.onnx"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 5,
      "created_at": "2020-03-12T17:48:30Z",
      "updated_at": "2020-03-13T17:59:05Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "## 🐛 Bug\r\n\r\nhttps://app.circleci.com/pipelines/github/pytorch/pytorch/138566/workflows/850299ec-3258-4e78-b680-cfad253c746a/jobs/4782754/parallel-runs/0/steps/0-105\r\n\r\n```\r\nMar 12 17:35:27 =================================== FAILURES ===================================\r\nMar 12 17:35:27 __________________ TestONNXRuntime_opset11.test_keypoint_rcnn __________________\r\nMar 12 17:35:27 \r\nMar 12 17:35:27 self = <test_pytorch_onnx_onnxruntime.TestONNXRuntime_opset11 testMethod=test_keypoint_rcnn>\r\nMar 12 17:35:27 \r\nMar 12 17:35:27     def wrapper(self):\r\nMar 12 17:35:27         if self.opset_version < min_opset_version:\r\nMar 12 17:35:27             raise unittest.SkipTest(\"Skip verify test for unsupported opset_version\")\r\nMar 12 17:35:27 >       return func(self)\r\nMar 12 17:35:27 \r\nMar 12 17:35:27 test/onnx/test_pytorch_common.py:54: \r\n```\r\n\n\ncc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34716",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34716/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34716/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34716/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34716",
      "id": 580678249,
      "node_id": "MDU6SXNzdWU1ODA2NzgyNDk=",
      "number": 34716,
      "title": "DISABLED test_stress_heavy_rpc_torchscript (__main__.RpcTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "zhaojuanmao",
        "id": 48731194,
        "node_id": "MDQ6VXNlcjQ4NzMxMTk0",
        "avatar_url": "https://avatars0.githubusercontent.com/u/48731194?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/zhaojuanmao",
        "html_url": "https://github.com/zhaojuanmao",
        "followers_url": "https://api.github.com/users/zhaojuanmao/followers",
        "following_url": "https://api.github.com/users/zhaojuanmao/following{/other_user}",
        "gists_url": "https://api.github.com/users/zhaojuanmao/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/zhaojuanmao/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/zhaojuanmao/subscriptions",
        "organizations_url": "https://api.github.com/users/zhaojuanmao/orgs",
        "repos_url": "https://api.github.com/users/zhaojuanmao/repos",
        "events_url": "https://api.github.com/users/zhaojuanmao/events{/privacy}",
        "received_events_url": "https://api.github.com/users/zhaojuanmao/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "zhaojuanmao",
          "id": 48731194,
          "node_id": "MDQ6VXNlcjQ4NzMxMTk0",
          "avatar_url": "https://avatars0.githubusercontent.com/u/48731194?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/zhaojuanmao",
          "html_url": "https://github.com/zhaojuanmao",
          "followers_url": "https://api.github.com/users/zhaojuanmao/followers",
          "following_url": "https://api.github.com/users/zhaojuanmao/following{/other_user}",
          "gists_url": "https://api.github.com/users/zhaojuanmao/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/zhaojuanmao/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/zhaojuanmao/subscriptions",
          "organizations_url": "https://api.github.com/users/zhaojuanmao/orgs",
          "repos_url": "https://api.github.com/users/zhaojuanmao/repos",
          "events_url": "https://api.github.com/users/zhaojuanmao/events{/privacy}",
          "received_events_url": "https://api.github.com/users/zhaojuanmao/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 3,
      "created_at": "2020-03-13T15:31:38Z",
      "updated_at": "2020-03-17T00:03:46Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "This is still flaky after #34505 \r\n\r\nhttps://app.circleci.com/pipelines/github/pytorch/pytorch/139235/workflows/eedfde36-e956-4d3f-952b-24fd62639d14/jobs/4801429\r\n\r\n```\r\nMar 13 15:10:46 .Process process 2:\r\nMar 13 15:10:46 Traceback (most recent call last):\r\nMar 13 15:10:46   File \"/opt/conda/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\r\nMar 13 15:10:46     self.run()\r\nMar 13 15:10:46   File \"/opt/conda/lib/python3.6/multiprocessing/process.py\", line 93, in run\r\nMar 13 15:10:46     self._target(*self._args, **self._kwargs)\r\nMar 13 15:10:46   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 243, in _run\r\nMar 13 15:10:46     getattr(self, test_name)()\r\nMar 13 15:10:46   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py\", line 68, in new_test_method\r\nMar 13 15:10:46     return_value = old_test_method(self, *arg, **kwargs)\r\nMar 13 15:10:46   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py\", line 856, in test_stress_heavy_rpc_torchscript\r\nMar 13 15:10:46     self._stress_test_rpc(heavy_rpc_torchscript, repeat=20, args=(torch.ones(100, 100),))\r\nMar 13 15:10:46   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py\", line 838, in _stress_test_rpc\r\nMar 13 15:10:46     self.assertEqual(fut.wait(), 0)\r\nMar 13 15:10:46 RuntimeError: RPC ran for more than 60000 milliseconds and timed out.\r\nMar 13 15:11:25 Timing out after 100 seconds and killing subprocesses.\r\nMar 13 15:11:27 ERank 2 finished testing 1000 times in 0.6682846546173096 seconds.\r\nMar 13 15:11:27 Rank 1 finished testing 1000 times in 0.6684725284576416 seconds.\r\nMar 13 15:11:27 Rank 0 finished testing 1000 times in 0.34218406677246094 seconds.\r\nMar 13 15:11:27 Rank 3 finished testing 1000 times in 0.4612858295440674 seconds.\r\nMar 13 15:11:31 ......\r\nMar 13 15:11:31 ======================================================================\r\nMar 13 15:11:31 ERROR [100.092s]: test_stress_heavy_rpc_torchscript (__main__.RpcTestWithSpawn)\r\nMar 13 15:11:31 ----------------------------------------------------------------------\r\nMar 13 15:11:31 Traceback (most recent call last):\r\nMar 13 15:11:31   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 175, in wrapper\r\nMar 13 15:11:31     self._join_processes(fn)\r\nMar 13 15:11:31   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 285, in _join_processes\r\nMar 13 15:11:31     self._check_return_codes(elapsed_time)\r\nMar 13 15:11:31   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 323, in _check_return_codes\r\nMar 13 15:11:31     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))\r\nMar 13 15:11:31 RuntimeError: Process 0 terminated or timed out after 100.08271050453186 seconds\r\n```\n\ncc @ezyang @gchanan @zou3519 @suo @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/32644",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/32644/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/32644/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/32644/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/32644",
      "id": 555422490,
      "node_id": "MDU6SXNzdWU1NTU0MjI0OTA=",
      "number": 32644,
      "title": "DISABLED test_quantized_rnn (test_quanization.PostTrainingDynamicQuantTest)",
      "user": {
        "login": "rohan-varma",
        "id": 8039770,
        "node_id": "MDQ6VXNlcjgwMzk3NzA=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/8039770?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rohan-varma",
        "html_url": "https://github.com/rohan-varma",
        "followers_url": "https://api.github.com/users/rohan-varma/followers",
        "following_url": "https://api.github.com/users/rohan-varma/following{/other_user}",
        "gists_url": "https://api.github.com/users/rohan-varma/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rohan-varma/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rohan-varma/subscriptions",
        "organizations_url": "https://api.github.com/users/rohan-varma/orgs",
        "repos_url": "https://api.github.com/users/rohan-varma/repos",
        "events_url": "https://api.github.com/users/rohan-varma/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rohan-varma/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1031340614,
          "node_id": "MDU6TGFiZWwxMDMxMzQwNjE0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/quantization",
          "name": "quantization",
          "color": "f7e101",
          "default": false,
          "description": "Quantization support in PyTorch"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "z-a-f",
        "id": 4216323,
        "node_id": "MDQ6VXNlcjQyMTYzMjM=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/4216323?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/z-a-f",
        "html_url": "https://github.com/z-a-f",
        "followers_url": "https://api.github.com/users/z-a-f/followers",
        "following_url": "https://api.github.com/users/z-a-f/following{/other_user}",
        "gists_url": "https://api.github.com/users/z-a-f/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/z-a-f/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/z-a-f/subscriptions",
        "organizations_url": "https://api.github.com/users/z-a-f/orgs",
        "repos_url": "https://api.github.com/users/z-a-f/repos",
        "events_url": "https://api.github.com/users/z-a-f/events{/privacy}",
        "received_events_url": "https://api.github.com/users/z-a-f/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "z-a-f",
          "id": 4216323,
          "node_id": "MDQ6VXNlcjQyMTYzMjM=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/4216323?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/z-a-f",
          "html_url": "https://github.com/z-a-f",
          "followers_url": "https://api.github.com/users/z-a-f/followers",
          "following_url": "https://api.github.com/users/z-a-f/following{/other_user}",
          "gists_url": "https://api.github.com/users/z-a-f/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/z-a-f/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/z-a-f/subscriptions",
          "organizations_url": "https://api.github.com/users/z-a-f/orgs",
          "repos_url": "https://api.github.com/users/z-a-f/repos",
          "events_url": "https://api.github.com/users/z-a-f/events{/privacy}",
          "received_events_url": "https://api.github.com/users/z-a-f/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 15,
      "created_at": "2020-01-27T08:22:49Z",
      "updated_at": "2020-03-06T03:05:33Z",
      "closed_at": null,
      "author_association": "MEMBER",
      "body": "## 🐛 Bug\r\n\r\ntes_quantized_rnn is flaky, see https://app.circleci.com/jobs/github/pytorch/pytorch/4343194\r\nSee example failure: \r\n```\r\nJan 26 08:10:23 ======================================================================\r\nJan 26 08:10:23 ERROR [0.186s]: test_quantized_rnn (__main__.PostTrainingDynamicQuantTest)\r\nJan 26 08:10:23 ----------------------------------------------------------------------\r\nJan 26 08:10:23 Traceback (most recent call last):\r\nJan 26 08:10:23   File \"test_quantization.py\", line 722, in test_quantized_rnn\r\nJan 26 08:10:23     y, (h, c) = cell_dq(x, (h, c))\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 540, in __call__\r\nJan 26 08:10:23     result = self.forward(*input, **kwargs)\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 373, in forward\r\nJan 26 08:10:23     return self.forward_tensor(input, hx)\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 334, in forward_tensor\r\nJan 26 08:10:23     input, hx, batch_sizes, max_batch_size, sorted_indices)\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 315, in forward_impl\r\nJan 26 08:10:23     self.batch_first, dtype=self.dtype, use_dynamic=True)\r\nJan 26 08:10:23 RuntimeError: quantization scale should be > 0\r\n```\n\ncc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34260",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34260/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34260/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34260/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34260",
      "id": 575758658,
      "node_id": "MDU6SXNzdWU1NzU3NTg2NTg=",
      "number": 34260,
      "title": "DISABLED test_torchscript_functions_not_supported (__main__.JitRpcTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "xush6528",
        "id": 7608630,
        "node_id": "MDQ6VXNlcjc2MDg2MzA=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/7608630?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/xush6528",
        "html_url": "https://github.com/xush6528",
        "followers_url": "https://api.github.com/users/xush6528/followers",
        "following_url": "https://api.github.com/users/xush6528/following{/other_user}",
        "gists_url": "https://api.github.com/users/xush6528/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/xush6528/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/xush6528/subscriptions",
        "organizations_url": "https://api.github.com/users/xush6528/orgs",
        "repos_url": "https://api.github.com/users/xush6528/repos",
        "events_url": "https://api.github.com/users/xush6528/events{/privacy}",
        "received_events_url": "https://api.github.com/users/xush6528/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "xush6528",
          "id": 7608630,
          "node_id": "MDQ6VXNlcjc2MDg2MzA=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/7608630?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/xush6528",
          "html_url": "https://github.com/xush6528",
          "followers_url": "https://api.github.com/users/xush6528/followers",
          "following_url": "https://api.github.com/users/xush6528/following{/other_user}",
          "gists_url": "https://api.github.com/users/xush6528/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/xush6528/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/xush6528/subscriptions",
          "organizations_url": "https://api.github.com/users/xush6528/orgs",
          "repos_url": "https://api.github.com/users/xush6528/repos",
          "events_url": "https://api.github.com/users/xush6528/events{/privacy}",
          "received_events_url": "https://api.github.com/users/xush6528/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 7,
      "created_at": "2020-03-04T20:48:06Z",
      "updated_at": "2020-03-19T01:08:19Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "test_torchscript_functions_not_supported is flaky\r\n\r\nPassed :\r\nhttps://app.circleci.com/jobs/github/pytorch/pytorch/4691744\r\n\r\nFailed:\r\nhttps://app.circleci.com/jobs/github/pytorch/pytorch/4692485\r\n\r\n```\r\nMar 04 20:33:44 Running tests...\r\nMar 04 20:33:44 ----------------------------------------------------------------------\r\nMar 04 20:33:48 ...[E request_callback.cpp:39] Received error while processing request type 0: attempted to get undefined function python_function (get_function at /var/lib/jenkins/workspace/torch/csrc/jit/api/compilation_unit.h:69)\r\nMar 04 20:33:48 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7f31d8c6679a in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\nMar 04 20:33:48 frame #1: <unknown function> + 0x65b5bd (0x7f31d98625bd in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:48 frame #2: torch::distributed::rpc::RequestCallbackImpl::processRpc(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType, long) const + 0x18dc (0x7f31d9aa823c in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:48 frame #3: torch::distributed::rpc::RequestCallbackImpl::processMessage(torch::distributed::rpc::Message&) const + 0x55 (0x7f31d9aa94a5 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:48 frame #4: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&) const + 0x33 (0x7f31d6579ed3 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\nMar 04 20:33:48 frame #5: <unknown function> + 0x88326b (0x7f31d9a8a26b in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:48 frame #6: c10::ThreadPool::main_loop(unsigned long) + 0x2fb (0x7f31d8c57cab in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\nMar 04 20:33:48 frame #7: <unknown function> + 0xc8421 (0x7f31d915b421 in /opt/conda/lib/libstdc++.so.6)\r\nMar 04 20:33:48 frame #8: <unknown function> + 0x76ba (0x7f31e1d666ba in /lib/x86_64-linux-gnu/libpthread.so.0)\r\nMar 04 20:33:48 frame #9: clone + 0x6d (0x7f31e1a9c41d in /lib/x86_64-linux-gnu/libc.so.6)\r\nMar 04 20:33:48 \r\nMar 04 20:33:49 .[E request_callback.cpp:39] Received error while processing request type 0: attempted to get undefined function nonexisting_script (get_function at /var/lib/jenkins/workspace/torch/csrc/jit/api/compilation_unit.h:69)\r\nMar 04 20:33:49 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7f800502a79a in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\nMar 04 20:33:49 frame #1: <unknown function> + 0x65b5bd (0x7f8005c265bd in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:49 frame #2: torch::distributed::rpc::RequestCallbackImpl::processRpc(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType, long) const + 0x18dc (0x7f8005e6c23c in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:49 frame #3: torch::distributed::rpc::RequestCallbackImpl::processMessage(torch::distributed::rpc::Message&) const + 0x55 (0x7f8005e6d4a5 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:49 frame #4: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&) const + 0x33 (0x7f800293ded3 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)\r\nMar 04 20:33:49 frame #5: <unknown function> + 0x88326b (0x7f8005e4e26b in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)\r\nMar 04 20:33:49 frame #6: c10::ThreadPool::main_loop(unsigned long) + 0x2fb (0x7f800501bcab in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)\r\nMar 04 20:33:49 frame #7: <unknown function> + 0xc8421 (0x7f800551f421 in /opt/conda/lib/libstdc++.so.6)\r\nMar 04 20:33:49 frame #8: <unknown function> + 0x76ba (0x7f800e12a6ba in /lib/x86_64-linux-gnu/libpthread.so.0)\r\nMar 04 20:33:49 frame #9: clone + 0x6d (0x7f800de6041d in /lib/x86_64-linux-gnu/libc.so.6)\r\nMar 04 20:33:49 \r\nMar 04 20:33:50 .[E request_callback.cpp:39] Received error while processing request type 0: The following operation failed in the TorchScript interpreter.\r\nMar 04 20:33:50 Traceback of TorchScript (most recent call last):\r\nMar 04 20:33:50   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py\", line 140, in raise_script\r\nMar 04 20:33:50 @torch.jit.script\r\nMar 04 20:33:50 def raise_script():\r\nMar 04 20:33:50     raise RuntimeError(\"Expected error\")\r\nMar 04 20:33:50     ~~~~~~~~~~~~~~~~~~~~ <--- HERE\r\nMar 04 20:33:50     return 0\r\nMar 04 20:33:50 RuntimeError: Exception\r\nMar 04 20:33:50 \r\nMar 04 20:35:07 ...............Process process 3:\r\nMar 04 20:35:07 Traceback (most recent call last):\r\nMar 04 20:35:07   File \"/opt/conda/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\r\nMar 04 20:35:07     self.run()\r\nMar 04 20:35:07   File \"/opt/conda/lib/python3.6/multiprocessing/process.py\", line 93, in run\r\nMar 04 20:35:07     self._target(*self._args, **self._kwargs)\r\nMar 04 20:35:07   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 243, in _run\r\nMar 04 20:35:07     getattr(self, test_name)()\r\nMar 04 20:35:07   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py\", line 68, in new_test_method\r\nMar 04 20:35:07     return_value = old_test_method(self, *arg, **kwargs)\r\nMar 04 20:35:07   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py\", line 496, in test_torchscript_functions_not_supported\r\nMar 04 20:35:07     ret = rpc.rpc_sync(\"worker{}\".format(dst_rank), MyScriptClass, args=())\r\nMar 04 20:35:07   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 76, in wrapper\r\nMar 04 20:35:07     return func(*args, **kwargs)\r\nMar 04 20:35:07   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 526, in rpc_sync\r\nMar 04 20:35:07     return fut.wait()\r\nMar 04 20:35:07 RuntimeError: RPC ran for more than 60000 milliseconds and timed out.\r\nMar 04 20:35:08 Process process 1:\r\nMar 04 20:35:08 Traceback (most recent call last):\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\r\nMar 04 20:35:08     self.run()\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/multiprocessing/process.py\", line 93, in run\r\nMar 04 20:35:08     self._target(*self._args, **self._kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 243, in _run\r\nMar 04 20:35:08     getattr(self, test_name)()\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py\", line 71, in new_test_method\r\nMar 04 20:35:08     rpc.shutdown(graceful=clean_shutdown)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 76, in wrapper\r\nMar 04 20:35:08     return func(*args, **kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 237, in shutdown\r\nMar 04 20:35:08     _wait_all_workers()\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 76, in wrapper\r\nMar 04 20:35:08     return func(*args, **kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 164, in _wait_all_workers\r\nMar 04 20:35:08     args=(sequence_id, self_worker_name,),\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 76, in wrapper\r\nMar 04 20:35:08     return func(*args, **kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 526, in rpc_sync\r\nMar 04 20:35:08     return fut.wait()\r\nMar 04 20:35:08 RuntimeError: RPC ran for more than 60000 milliseconds and timed out.\r\nMar 04 20:35:08 Process process 2:\r\nMar 04 20:35:08 Traceback (most recent call last):\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\r\nMar 04 20:35:08     self.run()\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/multiprocessing/process.py\", line 93, in run\r\nMar 04 20:35:08     self._target(*self._args, **self._kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 243, in _run\r\nMar 04 20:35:08     getattr(self, test_name)()\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py\", line 71, in new_test_method\r\nMar 04 20:35:08     rpc.shutdown(graceful=clean_shutdown)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 76, in wrapper\r\nMar 04 20:35:08     return func(*args, **kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 237, in shutdown\r\nMar 04 20:35:08     _wait_all_workers()\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 76, in wrapper\r\nMar 04 20:35:08     return func(*args, **kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 164, in _wait_all_workers\r\nMar 04 20:35:08     args=(sequence_id, self_worker_name,),\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 76, in wrapper\r\nMar 04 20:35:08     return func(*args, **kwargs)\r\nMar 04 20:35:08   File \"/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py\", line 526, in rpc_sync\r\nMar 04 20:35:08     return fut.wait()\r\nMar 04 20:35:08 RuntimeError: RPC ran for more than 60000 milliseconds and timed out.\r\nMar 04 20:35:48 E.\r\nMar 04 20:35:48 ======================================================================\r\nMar 04 20:35:48 ERROR [100.047s]: test_torchscript_functions_not_supported (__main__.JitRpcTestWithSpawn)\r\nMar 04 20:35:48 ----------------------------------------------------------------------\r\nMar 04 20:35:48 Traceback (most recent call last):\r\nMar 04 20:35:48   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 175, in wrapper\r\nMar 04 20:35:48     self._join_processes(fn)\r\nMar 04 20:35:48   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 256, in _join_processes\r\nMar 04 20:35:48     self._check_return_codes(elapsed_time)\r\nMar 04 20:35:48   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 275, in _check_return_codes\r\nMar 04 20:35:48     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))\r\nMar 04 20:35:48 RuntimeError: Process 0 terminated or timed out after 100.02777481079102 seconds\r\n```\n\ncc @ezyang @gchanan @zou3519 @suo @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34213",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34213/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34213/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34213/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34213",
      "id": 575502768,
      "node_id": "MDU6SXNzdWU1NzU1MDI3Njg=",
      "number": 34213,
      "title": "DISABLED test_script_pack_padded_sequence (test_jit.TestScript)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953983,
          "node_id": "MDU6TGFiZWw2Nzk5NTM5ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/jit",
          "name": "jit",
          "color": "c5def5",
          "default": false,
          "description": null
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-03-04T15:29:15Z",
      "updated_at": "2020-03-09T17:09:59Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "Previous failed runs:\r\nhttps://circleci.com/gh/pytorch/pytorch/4682966\r\n\r\nSubsequent succeeded runs:\r\nhttps://circleci.com/gh/pytorch/pytorch/4682247\r\nhttps://circleci.com/gh/pytorch/pytorch/4682241\r\n\r\nToday, it consistently fails:\r\nhttps://circleci.com/gh/pytorch/pytorch/4687625\r\nhttps://circleci.com/gh/pytorch/pytorch/4687610\r\nhttps://circleci.com/gh/pytorch/pytorch/4686149\r\n\r\n@ljk53 tried reverting the seemingly culprit PR #32814 and #34055, but the error persist. \r\n\r\nI am going to disable this test while JIT team investigating it. \n\ncc @ezyang @gchanan @zou3519 @suo",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34432",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34432/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34432/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34432/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34432",
      "id": 577434425,
      "node_id": "MDU6SXNzdWU1Nzc0MzQ0MjU=",
      "number": 34432,
      "title": "DISABLED test_gloo_backend_1gpu_module_device_ids_integer_list (__main__.DistributedDataParallelTest)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953883,
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20distributed",
          "name": "module: distributed",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.distributed"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-03-08T02:42:25Z",
      "updated_at": "2020-03-08T02:42:33Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/20231//console\r\n\r\n```\r\n22:09:03 ======================================================================\r\n22:09:03 FAIL: test_gloo_backend_1gpu_module_device_ids_integer_list (__main__.DistributedDataParallelTest)\r\n22:09:03 ----------------------------------------------------------------------\r\n22:09:03 Traceback (most recent call last):\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 175, in wrapper\r\n22:09:03     self._join_processes(fn)\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 256, in _join_processes\r\n22:09:03     self._check_return_codes(elapsed_time)\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 276, in _check_return_codes\r\n22:09:03     self.assertEqual(p.exitcode, first_process.exitcode)\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 915, in assertEqual\r\n22:09:03     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)\r\n22:09:03 AssertionError: 16 not less than or equal to 1e-05 : \r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/31750",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/31750/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/31750/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/31750/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/31750",
      "id": 544251558,
      "node_id": "MDU6SXNzdWU1NDQyNTE1NTg=",
      "number": 31750,
      "title": "DISABLED test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset10::test_interpolate_downsample",
      "user": {
        "login": "Krovatkin",
        "id": 5086322,
        "node_id": "MDQ6VXNlcjUwODYzMjI=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/5086322?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Krovatkin",
        "html_url": "https://github.com/Krovatkin",
        "followers_url": "https://api.github.com/users/Krovatkin/followers",
        "following_url": "https://api.github.com/users/Krovatkin/following{/other_user}",
        "gists_url": "https://api.github.com/users/Krovatkin/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Krovatkin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Krovatkin/subscriptions",
        "organizations_url": "https://api.github.com/users/Krovatkin/orgs",
        "repos_url": "https://api.github.com/users/Krovatkin/repos",
        "events_url": "https://api.github.com/users/Krovatkin/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Krovatkin/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1679533716,
          "node_id": "MDU6TGFiZWwxNjc5NTMzNzE2",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/skipped",
          "name": "skipped",
          "color": "bfdadc",
          "default": false,
          "description": "Denotes a (flaky) test currently skipped in CI."
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 2,
      "created_at": "2019-12-31T19:03:16Z",
      "updated_at": "2020-01-02T14:49:19Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "body": "Temporarily disabling a flakey test.",
      "score": 0.0
    }
  ]
}
