{
  "total_count": 20,
  "incomplete_results": false,
  "items": [
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/40434",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/40434/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/40434/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/40434/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/40434",
      "id": 643908803,
      "node_id": "MDU6SXNzdWU2NDM5MDg4MDM=",
      "number": 40434,
      "title": "DISABLED test_backward_ddp_inside (__main__.TestDdpUnderDistAutogradWrapper)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953883,
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20distributed",
          "name": "module: distributed",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.distributed"
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-06-23T14:51:40Z",
      "updated_at": "2020-06-23T14:51:46Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/184349/workflows/b01c5601-2b54-4717-89a6-0e66284d487c/jobs/5970923/steps\r\n\r\n```\r\nJun 22 20:31:55 ======================================================================\r\nJun 22 20:31:55 ERROR [61.489s]: test_backward_ddp_inside (__main__.TestDdpUnderDistAutogradWrapper)\r\nJun 22 20:31:55 ----------------------------------------------------------------------\r\nJun 22 20:31:55 Traceback (most recent call last):\r\nJun 22 20:31:55   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 204, in wrapper\r\nJun 22 20:31:55     self._join_processes(fn)\r\nJun 22 20:31:55   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 306, in _join_processes\r\nJun 22 20:31:55     self._check_return_codes(elapsed_time)\r\nJun 22 20:31:55   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 339, in _check_return_codes\r\nJun 22 20:31:55     raise RuntimeError(error)\r\nJun 22 20:31:55 RuntimeError: Processes 5 exited with error code 10\r\n```\r\n\r\n```\r\nJun 22 20:30:53   test_backward_ddp_inside (__main__.TestDdpUnderDistAutogradWrapper) ... 2020-06-22 20:30:53,172 ddp_under_dist_autograd_test.py:327 INFO p:process 2 t:MainThread: Running the trainer #2...\r\nJun 22 20:30:53 2020-06-22 20:30:53,172 ddp_under_dist_autograd_test.py:329 INFO p:process 2 t:MainThread: Initing trainer process group by trainer #2 with ranks [0, 1, 2, 3]\r\nJun 22 20:30:53 2020-06-22 20:30:53,172 ddp_under_dist_autograd_test.py:327 INFO p:process 1 t:MainThread: Running the trainer #1...\r\nJun 22 20:30:53 2020-06-22 20:30:53,172 ddp_under_dist_autograd_test.py:329 INFO p:process 1 t:MainThread: Initing trainer process group by trainer #1 with ranks [0, 1, 2, 3]\r\nJun 22 20:30:53 2020-06-22 20:30:53,172 ddp_under_dist_autograd_test.py:314 INFO p:process 4 t:MainThread: The remote worker is running.\r\nJun 22 20:30:53 2020-06-22 20:30:53,172 ddp_under_dist_autograd_test.py:327 INFO p:process 3 t:MainThread: Running the trainer #3...\r\nJun 22 20:30:53 2020-06-22 20:30:53,173 ddp_under_dist_autograd_test.py:329 INFO p:process 3 t:MainThread: Initing trainer process group by trainer #3 with ranks [0, 1, 2, 3]\r\nJun 22 20:30:53 2020-06-22 20:30:53,173 ddp_under_dist_autograd_test.py:327 INFO p:process 0 t:MainThread: Running the trainer #0...\r\nJun 22 20:30:53 2020-06-22 20:30:53,173 ddp_under_dist_autograd_test.py:346 INFO p:process 5 t:MainThread: Running the master process...\r\nJun 22 20:30:53 2020-06-22 20:30:53,173 ddp_under_dist_autograd_test.py:329 INFO p:process 0 t:MainThread: Initing trainer process group by trainer #0 with ranks [0, 1, 2, 3]\r\nJun 22 20:30:53 2020-06-22 20:30:53,176 ddp_under_dist_autograd_test.py:337 INFO p:process 0 t:MainThread: Waiting for shutdown signal on trainer #0...\r\nJun 22 20:30:53 2020-06-22 20:30:53,176 ddp_under_dist_autograd_test.py:360 INFO p:process 5 t:MainThread: Created remote rrefs on master\r\nJun 22 20:30:53 2020-06-22 20:30:53,198 ddp_under_dist_autograd_test.py:98 INFO p:process 4 t:Dummy-1: Initing RemoteEM with 2 3\r\nJun 22 20:30:53 2020-06-22 20:30:53,199 ddp_under_dist_autograd_test.py:124 INFO p:process 4 t:Dummy-2: Initing RemoteNet with 5 3\r\nJun 22 20:30:53 2020-06-22 20:30:53,200 ddp_under_dist_autograd_test.py:337 INFO p:process 2 t:MainThread: Waiting for shutdown signal on trainer #2...\r\nJun 22 20:30:53 2020-06-22 20:30:53,204 ddp_under_dist_autograd_test.py:337 INFO p:process 1 t:MainThread: Waiting for shutdown signal on trainer #1...\r\nJun 22 20:30:53 2020-06-22 20:30:53,204 ddp_under_dist_autograd_test.py:337 INFO p:process 3 t:MainThread: Waiting for shutdown signal on trainer #3...\r\nJun 22 20:31:53 ERROR:root:Caught exception: \r\nJun 22 20:31:53 Traceback (most recent call last):\r\nJun 22 20:31:53   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 207, in wrapper\r\nJun 22 20:31:53     fn()\r\nJun 22 20:31:53   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py\", line 93, in new_test_method\r\nJun 22 20:31:53     return_value = old_test_method(self, *arg, **kwargs)\r\nJun 22 20:31:53   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py\", line 445, in test_backward_ddp_inside\r\nJun 22 20:31:53     self._do_test(DdpMode.INSIDE)\r\nJun 22 20:31:53   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py\", line 424, in _do_test\r\nJun 22 20:31:53     self._master_process(ddp_mode)\r\nJun 22 20:31:53   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py\", line 361, in _master_process\r\nJun 22 20:31:53     self.do_test_on_master(ddp_mode, remote_em_rref, remote_net_rref)\r\nJun 22 20:31:53   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py\", line 393, in do_test_on_master\r\nJun 22 20:31:53     ddp_grads, non_ddp_grads = future.wait()\r\nJun 22 20:31:53 RuntimeError: RPCErr:1:RPC ran for more than 60000 milliseconds and timed out.\r\nJun 22 20:31:53 exiting process with exit code: 10\r\nJun 22 20:31:53 Process 5 terminated with exit code 10, terminating remaining processes.\r\nJun 22 20:31:53 ERROR (61.489s)\r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jjlilley",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/40378",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/40378/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/40378/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/40378/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/40378",
      "id": 643229664,
      "node_id": "MDU6SXNzdWU2NDMyMjk2NjQ=",
      "number": 40378,
      "title": "DISABLED test_backward_ddp_outside (__main__.TestDdpUnderDistAutogradWrapper)",
      "user": {
        "login": "rohan-varma",
        "id": 8039770,
        "node_id": "MDQ6VXNlcjgwMzk3NzA=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/8039770?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rohan-varma",
        "html_url": "https://github.com/rohan-varma",
        "followers_url": "https://api.github.com/users/rohan-varma/followers",
        "following_url": "https://api.github.com/users/rohan-varma/following{/other_user}",
        "gists_url": "https://api.github.com/users/rohan-varma/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rohan-varma/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rohan-varma/subscriptions",
        "organizations_url": "https://api.github.com/users/rohan-varma/orgs",
        "repos_url": "https://api.github.com/users/rohan-varma/repos",
        "events_url": "https://api.github.com/users/rohan-varma/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rohan-varma/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953883,
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20distributed",
          "name": "module: distributed",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.distributed"
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "pritamdamania87",
        "id": 9958665,
        "node_id": "MDQ6VXNlcjk5NTg2NjU=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/9958665?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/pritamdamania87",
        "html_url": "https://github.com/pritamdamania87",
        "followers_url": "https://api.github.com/users/pritamdamania87/followers",
        "following_url": "https://api.github.com/users/pritamdamania87/following{/other_user}",
        "gists_url": "https://api.github.com/users/pritamdamania87/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/pritamdamania87/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pritamdamania87/subscriptions",
        "organizations_url": "https://api.github.com/users/pritamdamania87/orgs",
        "repos_url": "https://api.github.com/users/pritamdamania87/repos",
        "events_url": "https://api.github.com/users/pritamdamania87/events{/privacy}",
        "received_events_url": "https://api.github.com/users/pritamdamania87/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "pritamdamania87",
          "id": 9958665,
          "node_id": "MDQ6VXNlcjk5NTg2NjU=",
          "avatar_url": "https://avatars1.githubusercontent.com/u/9958665?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/pritamdamania87",
          "html_url": "https://github.com/pritamdamania87",
          "followers_url": "https://api.github.com/users/pritamdamania87/followers",
          "following_url": "https://api.github.com/users/pritamdamania87/following{/other_user}",
          "gists_url": "https://api.github.com/users/pritamdamania87/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/pritamdamania87/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/pritamdamania87/subscriptions",
          "organizations_url": "https://api.github.com/users/pritamdamania87/orgs",
          "repos_url": "https://api.github.com/users/pritamdamania87/repos",
          "events_url": "https://api.github.com/users/pritamdamania87/events{/privacy}",
          "received_events_url": "https://api.github.com/users/pritamdamania87/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-06-22T17:03:46Z",
      "updated_at": "2020-06-22T19:52:13Z",
      "closed_at": null,
      "author_association": "MEMBER",
      "active_lock_reason": null,
      "body": "## 🐛  test_backward_ddp_outside is flaky\r\n\r\nSee for ex. https://app.circleci.com/pipelines/github/pytorch/pytorch/183902/workflows/9bbc51db-4c8e-4d47-92ea-a43fe60ac4ce/jobs/5952141/steps\r\n\r\n```\r\nJun 22 00:59:56 ======================================================================\r\nJun 22 00:59:56 ERROR [61.552s]: test_backward_ddp_outside (__main__.TestDdpUnderDistAutogradWrapper)\r\nJun 22 00:59:56 ----------------------------------------------------------------------\r\nJun 22 00:59:56 Traceback (most recent call last):\r\nJun 22 00:59:56   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 204, in wrapper\r\nJun 22 00:59:56     self._join_processes(fn)\r\nJun 22 00:59:56   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 306, in _join_processes\r\nJun 22 00:59:56     self._check_return_codes(elapsed_time)\r\nJun 22 00:59:56   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 339, in _check_return_codes\r\nJun 22 00:59:56     raise RuntimeError(error)\r\nJun 22 00:59:56 RuntimeError: Processes 5 exited with error code 10\r\nJun 22 00:59:56 \r\nJun 22 00:59:56 ----------------------------------------------------------------------\r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jjlilley",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/40303",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/40303/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/40303/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/40303/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/40303",
      "id": 642201370,
      "node_id": "MDU6SXNzdWU2NDIyMDEzNzA=",
      "number": 40303,
      "title": "DISABLED test_local_shutdown (__main__.TensorPipeAgentRpcTestWithSpawn)",
      "user": {
        "login": "lw",
        "id": 120810,
        "node_id": "MDQ6VXNlcjEyMDgxMA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/120810?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lw",
        "html_url": "https://github.com/lw",
        "followers_url": "https://api.github.com/users/lw/followers",
        "following_url": "https://api.github.com/users/lw/following{/other_user}",
        "gists_url": "https://api.github.com/users/lw/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lw/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lw/subscriptions",
        "organizations_url": "https://api.github.com/users/lw/orgs",
        "repos_url": "https://api.github.com/users/lw/repos",
        "events_url": "https://api.github.com/users/lw/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lw/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1986434179,
          "node_id": "MDU6TGFiZWwxOTg2NDM0MTc5",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20tensorpipe",
          "name": "module: tensorpipe",
          "color": "f7e845",
          "default": false,
          "description": "Related to Tensorpipe RPC Agent"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "lw",
        "id": 120810,
        "node_id": "MDQ6VXNlcjEyMDgxMA==",
        "avatar_url": "https://avatars1.githubusercontent.com/u/120810?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lw",
        "html_url": "https://github.com/lw",
        "followers_url": "https://api.github.com/users/lw/followers",
        "following_url": "https://api.github.com/users/lw/following{/other_user}",
        "gists_url": "https://api.github.com/users/lw/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lw/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lw/subscriptions",
        "organizations_url": "https://api.github.com/users/lw/orgs",
        "repos_url": "https://api.github.com/users/lw/repos",
        "events_url": "https://api.github.com/users/lw/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lw/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "lw",
          "id": 120810,
          "node_id": "MDQ6VXNlcjEyMDgxMA==",
          "avatar_url": "https://avatars1.githubusercontent.com/u/120810?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/lw",
          "html_url": "https://github.com/lw",
          "followers_url": "https://api.github.com/users/lw/followers",
          "following_url": "https://api.github.com/users/lw/following{/other_user}",
          "gists_url": "https://api.github.com/users/lw/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/lw/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/lw/subscriptions",
          "organizations_url": "https://api.github.com/users/lw/orgs",
          "repos_url": "https://api.github.com/users/lw/repos",
          "events_url": "https://api.github.com/users/lw/events{/privacy}",
          "received_events_url": "https://api.github.com/users/lw/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-06-19T20:24:20Z",
      "updated_at": "2020-06-19T20:24:25Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/183267/workflows/af7c3c56-4437-47f7-ad4c-f816e4485705/jobs/5930451/steps\r\n\r\n```\r\nJun 19 20:19:53 ======================================================================\r\nJun 19 20:19:53 ERROR [100.089s]: test_local_shutdown (__main__.TensorPipeAgentRpcTestWithSpawn)\r\nJun 19 20:19:53 ----------------------------------------------------------------------\r\nJun 19 20:19:53 Traceback (most recent call last):\r\nJun 19 20:19:53   File \"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py\", line 204, in wrapper\r\nJun 19 20:19:53     self._join_processes(fn)\r\nJun 19 20:19:53   File \"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py\", line 306, in _join_processes\r\nJun 19 20:19:53     self._check_return_codes(elapsed_time)\r\nJun 19 20:19:53   File \"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py\", line 344, in _check_return_codes\r\nJun 19 20:19:53     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))\r\nJun 19 20:19:53 RuntimeError: Process 0 terminated or timed out after 100.07188177108765 seconds\r\nJun 19 20:19:53 \r\nJun 19 20:19:53 ----------------------------------------------------------------------\r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/40292",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/40292/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/40292/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/40292/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/40292",
      "id": 642163954,
      "node_id": "MDU6SXNzdWU2NDIxNjM5NTQ=",
      "number": 40292,
      "title": "DISABLED test_backward_no_ddp (__main__.TestDdpUnderDistAutograd)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953883,
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20distributed",
          "name": "module: distributed",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.distributed"
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "pritamdamania87",
        "id": 9958665,
        "node_id": "MDQ6VXNlcjk5NTg2NjU=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/9958665?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/pritamdamania87",
        "html_url": "https://github.com/pritamdamania87",
        "followers_url": "https://api.github.com/users/pritamdamania87/followers",
        "following_url": "https://api.github.com/users/pritamdamania87/following{/other_user}",
        "gists_url": "https://api.github.com/users/pritamdamania87/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/pritamdamania87/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pritamdamania87/subscriptions",
        "organizations_url": "https://api.github.com/users/pritamdamania87/orgs",
        "repos_url": "https://api.github.com/users/pritamdamania87/repos",
        "events_url": "https://api.github.com/users/pritamdamania87/events{/privacy}",
        "received_events_url": "https://api.github.com/users/pritamdamania87/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "pritamdamania87",
          "id": 9958665,
          "node_id": "MDQ6VXNlcjk5NTg2NjU=",
          "avatar_url": "https://avatars1.githubusercontent.com/u/9958665?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/pritamdamania87",
          "html_url": "https://github.com/pritamdamania87",
          "followers_url": "https://api.github.com/users/pritamdamania87/followers",
          "following_url": "https://api.github.com/users/pritamdamania87/following{/other_user}",
          "gists_url": "https://api.github.com/users/pritamdamania87/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/pritamdamania87/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/pritamdamania87/subscriptions",
          "organizations_url": "https://api.github.com/users/pritamdamania87/orgs",
          "repos_url": "https://api.github.com/users/pritamdamania87/repos",
          "events_url": "https://api.github.com/users/pritamdamania87/events{/privacy}",
          "received_events_url": "https://api.github.com/users/pritamdamania87/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-06-19T18:55:15Z",
      "updated_at": "2020-06-19T19:08:10Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/183171/workflows/68944290-faa8-4a70-81e3-87dff178361c/jobs/5927395/steps\r\n\r\n```\r\nJun 19 10:33:18   test_backward_no_ddp (__main__.TestDdpUnderDistAutograd) ... 2020-06-19 10:33:18,805 test_ddp_under_dist_autograd.py:327 INFO p:process 0 t:MainThread: Running the trainer #0...\r\nJun 19 10:33:18 2020-06-19 10:33:18,805 test_ddp_under_dist_autograd.py:329 INFO p:process 0 t:MainThread: Initing trainer process group by trainer #0 with ranks [0, 1, 2, 3]\r\nJun 19 10:33:18 2020-06-19 10:33:18,805 test_ddp_under_dist_autograd.py:314 INFO p:process 4 t:MainThread: The remote worker is running.\r\nJun 19 10:33:18 2020-06-19 10:33:18,805 test_ddp_under_dist_autograd.py:327 INFO p:process 2 t:MainThread: Running the trainer #2...\r\nJun 19 10:33:18 2020-06-19 10:33:18,806 test_ddp_under_dist_autograd.py:329 INFO p:process 2 t:MainThread: Initing trainer process group by trainer #2 with ranks [0, 1, 2, 3]\r\nJun 19 10:33:18 2020-06-19 10:33:18,805 test_ddp_under_dist_autograd.py:327 INFO p:process 3 t:MainThread: Running the trainer #3...\r\nJun 19 10:33:18 2020-06-19 10:33:18,806 test_ddp_under_dist_autograd.py:329 INFO p:process 3 t:MainThread: Initing trainer process group by trainer #3 with ranks [0, 1, 2, 3]\r\nJun 19 10:33:18 2020-06-19 10:33:18,806 test_ddp_under_dist_autograd.py:327 INFO p:process 1 t:MainThread: Running the trainer #1...\r\nJun 19 10:33:18 2020-06-19 10:33:18,806 test_ddp_under_dist_autograd.py:346 INFO p:process 5 t:MainThread: Running the master process...\r\nJun 19 10:33:18 2020-06-19 10:33:18,807 test_ddp_under_dist_autograd.py:329 INFO p:process 1 t:MainThread: Initing trainer process group by trainer #1 with ranks [0, 1, 2, 3]\r\nJun 19 10:33:18 2020-06-19 10:33:18,809 test_ddp_under_dist_autograd.py:337 INFO p:process 1 t:MainThread: Waiting for shutdown signal on trainer #1...\r\nJun 19 10:33:18 2020-06-19 10:33:18,811 test_ddp_under_dist_autograd.py:360 INFO p:process 5 t:MainThread: Created remote rrefs on master\r\nJun 19 10:33:18 2020-06-19 10:33:18,841 test_ddp_under_dist_autograd.py:98 INFO p:process 4 t:Dummy-1: Initing RemoteEM with 2 3\r\nJun 19 10:33:18 2020-06-19 10:33:18,843 test_ddp_under_dist_autograd.py:124 INFO p:process 4 t:Dummy-2: Initing RemoteNet with 5 3\r\nJun 19 10:33:18 2020-06-19 10:33:18,851 test_ddp_under_dist_autograd.py:337 INFO p:process 0 t:MainThread: Waiting for shutdown signal on trainer #0...\r\nJun 19 10:33:18 2020-06-19 10:33:18,851 test_ddp_under_dist_autograd.py:337 INFO p:process 2 t:MainThread: Waiting for shutdown signal on trainer #2...\r\nJun 19 10:33:18 2020-06-19 10:33:18,851 test_ddp_under_dist_autograd.py:337 INFO p:process 3 t:MainThread: Waiting for shutdown signal on trainer #3...\r\nJun 19 10:33:18 ERROR:root:Caught exception: \r\nJun 19 10:33:18 Traceback (most recent call last):\r\nJun 19 10:33:18   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 207, in wrapper\r\nJun 19 10:33:18     fn()\r\nJun 19 10:33:18   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py\", line 93, in new_test_method\r\nJun 19 10:33:18     return_value = old_test_method(self, *arg, **kwargs)\r\nJun 19 10:33:18   File \"/Users/distiller/project/test/distributed/test_ddp_under_dist_autograd.py\", line 435, in test_backward_no_ddp\r\nJun 19 10:33:18     self._do_test(DdpMode.NONE)\r\nJun 19 10:33:18   File \"/Users/distiller/project/test/distributed/test_ddp_under_dist_autograd.py\", line 424, in _do_test\r\nJun 19 10:33:18     self._master_process(ddp_mode)\r\nJun 19 10:33:18   File \"/Users/distiller/project/test/distributed/test_ddp_under_dist_autograd.py\", line 361, in _master_process\r\nJun 19 10:33:18     self.do_test_on_master(ddp_mode, remote_em_rref, remote_net_rref)\r\nJun 19 10:33:18   File \"/Users/distiller/project/test/distributed/test_ddp_under_dist_autograd.py\", line 393, in do_test_on_master\r\nJun 19 10:33:18     ddp_grads, non_ddp_grads = future.wait()\r\nJun 19 10:33:18   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/internal.py\", line 173, in _handle_exception\r\nJun 19 10:33:18     raise result.exception_type(result.msg)\r\nJun 19 10:33:18 AssertionError: On WorkerInfo(id=0, name=worker0):\r\nJun 19 10:33:18 AssertionError('On WorkerInfo(id=0, name=worker0):\\nAssertionError(\\'Default process group is not initialized\\')\\nTraceback (most recent call last):\\n  File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/internal.py\", line 160, in _run_function\\n    result = python_udf.func(*python_udf.args, **python_udf.kwargs)\\n  File \"/Users/distiller/project/test/distributed/test_ddp_under_dist_autograd.py\", line 191, in __init__\\n    self.trainer_group = dist.new_group(TRAINER_RANKS)\\n  File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py\", line 1745, in new_group\\n    _check_default_pg()\\n  File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py\", line 210, in _check_default_pg\\n    \"Default process group is not initialized\"\\nAssertionError: Default process group is not initialized\\n')\r\nJun 19 10:33:18 Traceback (most recent call last):\r\nJun 19 10:33:18   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/internal.py\", line 160, in _run_function\r\nJun 19 10:33:18     result = python_udf.func(*python_udf.args, **python_udf.kwargs)\r\nJun 19 10:33:18   File \"/Users/distiller/project/test/distributed/test_ddp_under_dist_autograd.py\", line 79, in _call_method\r\nJun 19 10:33:18     return method(rref.local_value(), *args, **kwargs)\r\nJun 19 10:33:18   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/internal.py\", line 173, in _handle_exception\r\nJun 19 10:33:18     raise result.exception_type(result.msg)\r\nJun 19 10:33:18 AssertionError: On WorkerInfo(id=0, name=worker0):\r\nJun 19 10:33:18 AssertionError('Default process group is not initialized')\r\nJun 19 10:33:18 Traceback (most recent call last):\r\nJun 19 10:33:18   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/internal.py\", line 160, in _run_function\r\nJun 19 10:33:18     result = python_udf.func(*python_udf.args, **python_udf.kwargs)\r\nJun 19 10:33:18   File \"/Users/distiller/project/test/distributed/test_ddp_under_dist_autograd.py\", line 191, in __init__\r\nJun 19 10:33:18     self.trainer_group = dist.new_group(TRAINER_RANKS)\r\nJun 19 10:33:18   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py\", line 1745, in new_group\r\nJun 19 10:33:18     _check_default_pg()\r\nJun 19 10:33:18   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py\", line 210, in _check_default_pg\r\nJun 19 10:33:18     \"Default process group is not initialized\"\r\nJun 19 10:33:18 AssertionError: Default process group is not initialized\r\nJun 19 10:33:18 \r\nJun 19 10:33:18 \r\nJun 19 10:33:18 exiting process with exit code: 10\r\nJun 19 10:33:18 Process 5 terminated with exit code 10, terminating remaining processes.\r\nJun 19 10:33:19 ERROR (1.565s)\r\n```\r\n\r\n```\r\nJun 19 10:33:19 ======================================================================\r\nJun 19 10:33:19 ERROR [1.565s]: test_backward_no_ddp (__main__.TestDdpUnderDistAutograd)\r\nJun 19 10:33:19 ----------------------------------------------------------------------\r\nJun 19 10:33:19 Traceback (most recent call last):\r\nJun 19 10:33:19   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 204, in wrapper\r\nJun 19 10:33:19     self._join_processes(fn)\r\nJun 19 10:33:19   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 306, in _join_processes\r\nJun 19 10:33:19     self._check_return_codes(elapsed_time)\r\nJun 19 10:33:19   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 339, in _check_return_codes\r\nJun 19 10:33:19     raise RuntimeError(error)\r\nJun 19 10:33:19 RuntimeError: Processes 5 exited with error code 10\r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jjlilley",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/38491",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/38491/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/38491/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/38491/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/38491",
      "id": 618421559,
      "node_id": "MDU6SXNzdWU2MTg0MjE1NTk=",
      "number": 38491,
      "title": "DISABLED ParallelWorkersTest.testParallelWorkersShutdownFun ",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 693805995,
          "node_id": "MDU6TGFiZWw2OTM4MDU5OTU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20onnx",
          "name": "module: onnx",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.onnx"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-05-14T17:45:34Z",
      "updated_at": "2020-05-14T17:45:40Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/169923/workflows/d66ca278-d55c-462b-96cb-55623ce713f7/jobs/5472514/steps\r\n\r\n```\r\nMay 14 07:37:27 =================================== FAILURES ===================================\r\nMay 14 07:37:27 ______________ ParallelWorkersTest.testParallelWorkersShutdownFun ______________\r\nMay 14 07:37:27 \r\nMay 14 07:37:27 self = <caffe2.python.parallel_workers_test.ParallelWorkersTest testMethod=testParallelWorkersShutdownFun>\r\nMay 14 07:37:27 \r\nMay 14 07:37:27     def testParallelWorkersShutdownFun(self):\r\nMay 14 07:37:27         workspace.ResetWorkspace()\r\nMay 14 07:37:27     \r\nMay 14 07:37:27         queue = create_queue()\r\nMay 14 07:37:27         dummy_worker = create_worker(queue, lambda worker_id: str(worker_id))\r\nMay 14 07:37:27         workspace.FeedBlob('data', 'not shutdown')\r\nMay 14 07:37:27     \r\nMay 14 07:37:27         def shutdown_fun():\r\nMay 14 07:37:27             workspace.FeedBlob('data', 'shutdown')\r\nMay 14 07:37:27     \r\nMay 14 07:37:27         worker_coordinator = parallel_workers.init_workers(\r\nMay 14 07:37:27             dummy_worker, shutdown_fun=shutdown_fun\r\nMay 14 07:37:27         )\r\nMay 14 07:37:27         worker_coordinator.start()\r\nMay 14 07:37:27     \r\nMay 14 07:37:27 >       self.assertTrue(worker_coordinator.stop())\r\nMay 14 07:37:27 E       AssertionError: False is not true\r\nMay 14 07:37:27 \r\nMay 14 07:37:27 ../.local/lib/python3.6/site-packages/caffe2/python/parallel_workers_test.py:116: AssertionError\r\nMay 14 07:37:27 ----------------------------- Captured stdout call -----------------------------\r\n```\n\ncc @ezyang @gchanan @zou3519 @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/39855",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/39855/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/39855/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/39855/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/39855",
      "id": 637037443,
      "node_id": "MDU6SXNzdWU2MzcwMzc0NDM=",
      "number": 39855,
      "title": "DISABLED test_backward_node_failure (__main__.TensorPipeAgentDistAutogradTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1076922545,
          "node_id": "MDU6TGFiZWwxMDc2OTIyNTQ1",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20autograd",
          "name": "module: autograd",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.autograd, and the autograd engine in general"
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1986434179,
          "node_id": "MDU6TGFiZWwxOTg2NDM0MTc5",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20tensorpipe",
          "name": "module: tensorpipe",
          "color": "f7e845",
          "default": false,
          "description": "Related to Tensorpipe RPC Agent"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 3,
      "created_at": "2020-06-11T13:55:45Z",
      "updated_at": "2020-06-18T13:53:31Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/179019/workflows/89ef9bec-c13c-4d81-a817-5de5fed67cdf/jobs/5772385/steps https://app.circleci.com/pipelines/github/pytorch/pytorch/179483/workflows/b1faffb1-687b-4000-bae1-37fa2c93d7f5/jobs/5787474/steps\r\n\r\n```\r\nJun 10 18:19:54   test_backward_node_failure (__main__.TensorPipeAgentDistAutogradTestWithSpawn) ... [W tensorpipe_agent.cpp:315] RPC agent for worker3 encountered error when reading incoming request: pipe closed\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:315] RPC agent for worker1 encountered error when reading incoming request: pipe closed\r\nJun 10 18:19:54 [E container.cpp:248] Could not release Dist Autograd Context on node 0: pipe closed\r\nJun 10 18:19:54 [E container.cpp:248] Could not release Dist Autograd Context on node 2: pipe closed\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker0 encountered error when writing outgoing request: EPIPE: broken pipe\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker2 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:315] RPC agent for worker0 encountered error when reading incoming request: EOF: end of file\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker0 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker0 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:283] RPC agent for worker0 encountered error when writing outgoing response: EOF: end of file\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker0 encountered error when writing outgoing request: EPIPE: broken pipe\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker2 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:315] RPC agent for worker2 encountered error when reading incoming request: EPIPE: broken pipe\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker0 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker0 encountered error when writing outgoing request: EPIPE: broken pipe\r\nJun 10 18:19:54 [E container.cpp:248] Could not release Dist Autograd Context on node 3: ECONNREFUSED: connection refused\r\nJun 10 18:19:54 [E container.cpp:248] Could not release Dist Autograd Context on node 1: EPIPE: broken pipe\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:283] RPC agent for worker2 encountered error when writing outgoing response: EPIPE: broken pipe\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker2 encountered error when writing outgoing request: EPIPE: broken pipe\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker2 encountered error when writing outgoing request: EPIPE: broken pipe\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker2 encountered error when writing outgoing request: ECONNREFUSED: connection refused\r\nJun 10 18:19:54 [W tensorpipe_agent.cpp:439] RPC agent for worker2 encountered error when writing outgoing request: EPIPE: broken pipe\r\nJun 10 18:21:33 Timing out after 100 seconds and killing subprocesses.\r\nJun 10 18:21:33 ERROR (100.075s)\r\n```\r\n\r\n```\r\nJun 10 18:24:42 ======================================================================\r\nJun 10 18:24:42 ERROR [100.075s]: test_backward_node_failure (__main__.TensorPipeAgentDistAutogradTestWithSpawn)\r\nJun 10 18:24:42 ----------------------------------------------------------------------\r\nJun 10 18:24:42 Traceback (most recent call last):\r\nJun 10 18:24:42   File \"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py\", line 204, in wrapper\r\nJun 10 18:24:42     self._join_processes(fn)\r\nJun 10 18:24:42   File \"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py\", line 306, in _join_processes\r\nJun 10 18:24:42     self._check_return_codes(elapsed_time)\r\nJun 10 18:24:42   File \"/opt/conda/lib/python3.8/site-packages/torch/testing/_internal/common_distributed.py\", line 344, in _check_return_codes\r\nJun 10 18:24:42     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))\r\nJun 10 18:24:42 RuntimeError: Process 2 terminated or timed out after 100.05913996696472 seconds\r\nJun 10 18:24:42 \r\nJun 10 18:24:42 ----------------------------------------------------------------------\r\n```\n\ncc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse @lw @beauby",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/40453",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/40453/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/40453/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/40453/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/40453",
      "id": 644064910,
      "node_id": "MDU6SXNzdWU2NDQwNjQ5MTA=",
      "number": 40453,
      "title": "DISABLED test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparisonTensorPipe)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953883,
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20distributed",
          "name": "module: distributed",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.distributed"
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1986434179,
          "node_id": "MDU6TGFiZWwxOTg2NDM0MTc5",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20tensorpipe",
          "name": "module: tensorpipe",
          "color": "f7e845",
          "default": false,
          "description": "Related to Tensorpipe RPC Agent"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-06-23T18:46:55Z",
      "updated_at": "2020-06-23T18:47:01Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "Similar to #40435, very like this is **not** caused by TensorPipe.\r\n\r\nhttps://app.circleci.com/pipelines/github/pytorch/pytorch/184590/workflows/0a65582a-2068-4803-9bbc-35c220afcf8f/jobs/5978379/steps\r\n\r\nhttps://app.circleci.com/pipelines/github/pytorch/pytorch/184559/workflows/5cfef953-6647-4916-b3ba-ee2c439ae652/jobs/5977287/steps\r\n\r\n```\r\nJun 23 11:43:34 ======================================================================\r\nJun 23 11:43:34 ERROR [62.283s]: test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparisonTensorPipe)\r\nJun 23 11:43:34 ----------------------------------------------------------------------\r\nJun 23 11:43:34 Traceback (most recent call last):\r\nJun 23 11:43:34   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 204, in wrapper\r\nJun 23 11:43:34     self._join_processes(fn)\r\nJun 23 11:43:34   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 306, in _join_processes\r\nJun 23 11:43:34     self._check_return_codes(elapsed_time)\r\nJun 23 11:43:34   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 339, in _check_return_codes\r\nJun 23 11:43:34     raise RuntimeError(error)\r\nJun 23 11:43:34 RuntimeError: Processes 3 exited with error code 10\r\n```\r\n\r\n```\r\nJun 23 11:43:18   test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparisonTensorPipe) ... ERROR:root:Caught exception: \r\nJun 23 11:43:18 Traceback (most recent call last):\r\nJun 23 11:43:18   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 207, in wrapper\r\nJun 23 11:43:18     fn()\r\nJun 23 11:43:18   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py\", line 93, in new_test_method\r\nJun 23 11:43:18     return_value = old_test_method(self, *arg, **kwargs)\r\nJun 23 11:43:18   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py\", line 571, in test_ddp_dist_autograd_local_vs_remote\r\nJun 23 11:43:18     layer1.weight = remote_layer1.module_rref.to_here().weight\r\nJun 23 11:43:18 RuntimeError: RPCErr:1:RPC ran for more than set timeout (60000 ms) and will now be marked with an error\r\nJun 23 11:43:18 exiting process with exit code: 10\r\nJun 23 11:43:18 [W tensorpipe_agent.cpp:491] RPC agent for worker0 encountered error when reading incoming request from worker3: EOF: end of file (this is expected to happen during shutdown)\r\nJun 23 11:43:18 Process 3 terminated with exit code 10, terminating remaining processes.\r\nJun 23 11:43:18 ERROR (62.283s)\r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jjlilley @jiayisuse @lw @beauby",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/40435",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/40435/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/40435/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/40435/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/40435",
      "id": 643909989,
      "node_id": "MDU6SXNzdWU2NDM5MDk5ODk=",
      "number": 40435,
      "title": "DISABLED test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparison)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953883,
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20distributed",
          "name": "module: distributed",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.distributed"
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-06-23T14:53:11Z",
      "updated_at": "2020-06-23T14:53:15Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/184408/workflows/fc2c5be1-9269-4d74-9c9d-4f7947f9a2c8/jobs/5971378/steps\r\n\r\n```\r\nJun 22 21:21:42 ======================================================================\r\nJun 22 21:21:42 ERROR [61.059s]: test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparison)\r\nJun 22 21:21:42 ----------------------------------------------------------------------\r\nJun 22 21:21:42 Traceback (most recent call last):\r\nJun 22 21:21:42   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 204, in wrapper\r\nJun 22 21:21:42     self._join_processes(fn)\r\nJun 22 21:21:42   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 306, in _join_processes\r\nJun 22 21:21:42     self._check_return_codes(elapsed_time)\r\nJun 22 21:21:42   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 339, in _check_return_codes\r\nJun 22 21:21:42     raise RuntimeError(error)\r\nJun 22 21:21:42 RuntimeError: Processes 3 exited with error code 10\r\n```\r\n\r\n```\r\nJun 22 21:21:37   test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparison) ... ERROR:root:Caught exception: \r\nJun 22 21:21:37 Traceback (most recent call last):\r\nJun 22 21:21:37   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 207, in wrapper\r\nJun 22 21:21:37     fn()\r\nJun 22 21:21:37   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py\", line 93, in new_test_method\r\nJun 22 21:21:37     return_value = old_test_method(self, *arg, **kwargs)\r\nJun 22 21:21:37   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py\", line 566, in test_ddp_dist_autograd_local_vs_remote\r\nJun 22 21:21:37     remote_layer1 = RemoteModule(\"worker0\", nn.Linear, args=(10, 5, False))\r\nJun 22 21:21:37   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/nn/api/remote_module.py\", line 215, in __init__\r\nJun 22 21:21:37     super().__init__(on, module_cls, args, kwargs)\r\nJun 22 21:21:37   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/nn/api/remote_module.py\", line 137, in __init__\r\nJun 22 21:21:37     (module_cls, args, kwargs, _module_interface_cls),\r\nJun 22 21:21:37   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/api.py\", line 80, in wrapper\r\nJun 22 21:21:37     return func(*args, **kwargs)\r\nJun 22 21:21:37   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/distributed/rpc/api.py\", line 711, in rpc_sync\r\nJun 22 21:21:37     return fut.wait()\r\nJun 22 21:21:37 RuntimeError: RPCErr:1:RPC ran for more than 60000 milliseconds and timed out.\r\nJun 22 21:21:37 exiting process with exit code: 10\r\nJun 22 21:21:37 Process 3 terminated with exit code 10, terminating remaining processes.\r\nJun 22 21:21:37 ERROR (61.059s)\r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jjlilley",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/40433",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/40433/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/40433/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/40433/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/40433",
      "id": 643882193,
      "node_id": "MDU6SXNzdWU2NDM4ODIxOTM=",
      "number": 40433,
      "title": "DISABLED test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparison)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953883,
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20distributed",
          "name": "module: distributed",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.distributed"
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 1,
      "created_at": "2020-06-23T14:18:30Z",
      "updated_at": "2020-06-23T14:56:36Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/184408/workflows/fc2c5be1-9269-4d74-9c9d-4f7947f9a2c8/jobs/5971373/steps\r\n\r\n```\r\nJun 23 04:22:14 ======================================================================\r\nJun 23 04:22:14 ERROR [61.183s]: test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparison)\r\nJun 23 04:22:14 ----------------------------------------------------------------------\r\nJun 23 04:22:14 Traceback (most recent call last):\r\nJun 23 04:22:14   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 204, in wrapper\r\nJun 23 04:22:14     self._join_processes(fn)\r\nJun 23 04:22:14   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 306, in _join_processes\r\nJun 23 04:22:14     self._check_return_codes(elapsed_time)\r\nJun 23 04:22:14   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 339, in _check_return_codes\r\nJun 23 04:22:14     raise RuntimeError(error)\r\nJun 23 04:22:14 RuntimeError: Processes 3 exited with error code 10\r\n```\r\n\r\n\r\n```\r\nJun 23 04:22:08   test_ddp_dist_autograd_local_vs_remote (__main__.TestDdpComparison) ... ERROR:root:Caught exception: \r\nJun 23 04:22:08 Traceback (most recent call last):\r\nJun 23 04:22:08   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 207, in wrapper\r\nJun 23 04:22:08     fn()\r\nJun 23 04:22:08   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py\", line 93, in new_test_method\r\nJun 23 04:22:08     return_value = old_test_method(self, *arg, **kwargs)\r\nJun 23 04:22:08   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py\", line 569, in test_ddp_dist_autograd_local_vs_remote\r\nJun 23 04:22:08     layer1.weight = remote_layer1.module_rref.to_here().weight\r\nJun 23 04:22:08 RuntimeError: RPCErr:1:RPC ran for more than 60000 milliseconds and timed out.\r\nJun 23 04:22:08 exiting process with exit code: 10\r\nJun 23 04:22:08 ERROR:root:Caught exception: \r\nJun 23 04:22:08 Traceback (most recent call last):\r\nJun 23 04:22:08   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 207, in wrapper\r\nJun 23 04:22:08     fn()\r\nJun 23 04:22:08   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py\", line 93, in new_test_method\r\nJun 23 04:22:08     return_value = old_test_method(self, *arg, **kwargs)\r\nJun 23 04:22:08   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py\", line 574, in test_ddp_dist_autograd_local_vs_remote\r\nJun 23 04:22:08     ddp_model = DistributedDataParallel(layer2)\r\nJun 23 04:22:08   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/nn/parallel/distributed.py\", line 329, in __init__\r\nJun 23 04:22:08     self.broadcast_bucket_size)\r\nJun 23 04:22:08   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/nn/parallel/distributed.py\", line 545, in _distributed_broadcast_coalesced\r\nJun 23 04:22:08     dist._broadcast_coalesced(self.process_group, tensors, buffer_size)\r\nJun 23 04:22:08 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:14761\r\nJun 23 04:22:08 exiting process with exit code: 10\r\nJun 23 04:22:08 ERROR:root:Caught exception: \r\nJun 23 04:22:08 Traceback (most recent call last):\r\nJun 23 04:22:08   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 207, in wrapper\r\nJun 23 04:22:08     fn()\r\nJun 23 04:22:08   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/dist_utils.py\", line 93, in new_test_method\r\nJun 23 04:22:08     return_value = old_test_method(self, *arg, **kwargs)\r\nJun 23 04:22:08   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/testing/_internal/distributed/ddp_under_dist_autograd_test.py\", line 576, in test_ddp_dist_autograd_local_vs_remote\r\nJun 23 04:22:08     loss.backward()\r\nJun 23 04:22:08   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/tensor.py\", line 185, in backward\r\nJun 23 04:22:08     torch.autograd.backward(self, gradient, retain_graph, create_graph)\r\nJun 23 04:22:08   File \"/opt/python/nightly/lib/python3.7/site-packages/torch/autograd/__init__.py\", line 127, in backward\r\nJun 23 04:22:08     allow_unreachable=True)  # allow_unreachable flag\r\nJun 23 04:22:08 RuntimeError: [/var/lib/jenkins/workspace/third_party/gloo/gloo/transport/tcp/pair.cc:575] Connection closed by peer [172.17.0.2]:31108\r\nJun 23 04:22:08 exiting process with exit code: 10\r\nJun 23 04:22:08 Process 3 terminated with exit code 10, terminating remaining processes.\r\nJun 23 04:22:08 ERROR (61.183s)\r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jjlilley",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/39445",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/39445/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/39445/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/39445/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/39445",
      "id": 630008873,
      "node_id": "MDU6SXNzdWU2MzAwMDg4NzM=",
      "number": 39445,
      "title": "DISABLED test_graph_for_python_remote_call (__main__.DistAutogradTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-06-03T13:46:42Z",
      "updated_at": "2020-06-03T13:46:47Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/176130/workflows/56fefa1d-d892-4af3-9469-5eaaa22b1d0b/jobs/5658716/steps\r\n\r\nObserved on tests for commit 09bea1398141e0f74afb1e22d380d3322ba28105\r\n\r\n```\r\nJun 02 21:11:00   test_graph_for_python_remote_call (__main__.DistAutogradTestWithSpawn) ... Timing out after 100 seconds and killing subprocesses.\r\nJun 02 21:11:00 ERROR (100.099s)\r\n```\r\n\r\n\r\n```\r\nJun 02 21:11:25 ======================================================================\r\nJun 02 21:11:25 ERROR [100.099s]: test_graph_for_python_remote_call (__main__.DistAutogradTestWithSpawn)\r\nJun 02 21:11:25 ----------------------------------------------------------------------\r\nJun 02 21:11:25 Traceback (most recent call last):\r\nJun 02 21:11:25   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 204, in wrapper\r\nJun 02 21:11:25     self._join_processes(fn)\r\nJun 02 21:11:25   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 306, in _join_processes\r\nJun 02 21:11:25     self._check_return_codes(elapsed_time)\r\nJun 02 21:11:25   File \"/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 344, in _check_return_codes\r\nJun 02 21:11:25     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))\r\nJun 02 21:11:25 RuntimeError: Process 0 terminated or timed out after 100.07846069335938 seconds\r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/36332",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/36332/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/36332/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/36332/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/36332",
      "id": 597507619,
      "node_id": "MDU6SXNzdWU1OTc1MDc2MTk=",
      "number": 36332,
      "title": "DISABLED test_check_failed_messages (__main__.FaultyAgentRpcTestWithSpawn)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "osalpekar",
        "id": 14008860,
        "node_id": "MDQ6VXNlcjE0MDA4ODYw",
        "avatar_url": "https://avatars2.githubusercontent.com/u/14008860?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/osalpekar",
        "html_url": "https://github.com/osalpekar",
        "followers_url": "https://api.github.com/users/osalpekar/followers",
        "following_url": "https://api.github.com/users/osalpekar/following{/other_user}",
        "gists_url": "https://api.github.com/users/osalpekar/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/osalpekar/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/osalpekar/subscriptions",
        "organizations_url": "https://api.github.com/users/osalpekar/orgs",
        "repos_url": "https://api.github.com/users/osalpekar/repos",
        "events_url": "https://api.github.com/users/osalpekar/events{/privacy}",
        "received_events_url": "https://api.github.com/users/osalpekar/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "osalpekar",
          "id": 14008860,
          "node_id": "MDQ6VXNlcjE0MDA4ODYw",
          "avatar_url": "https://avatars2.githubusercontent.com/u/14008860?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/osalpekar",
          "html_url": "https://github.com/osalpekar",
          "followers_url": "https://api.github.com/users/osalpekar/followers",
          "following_url": "https://api.github.com/users/osalpekar/following{/other_user}",
          "gists_url": "https://api.github.com/users/osalpekar/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/osalpekar/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/osalpekar/subscriptions",
          "organizations_url": "https://api.github.com/users/osalpekar/orgs",
          "repos_url": "https://api.github.com/users/osalpekar/repos",
          "events_url": "https://api.github.com/users/osalpekar/events{/privacy}",
          "received_events_url": "https://api.github.com/users/osalpekar/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 2,
      "created_at": "2020-04-09T19:36:45Z",
      "updated_at": "2020-05-19T22:50:22Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "https://app.circleci.com/pipelines/github/pytorch/pytorch/153028/workflows/c3ba2031-4e43-41d4-8399-c69cd09b49d7/jobs/5100538\r\n\r\n```\r\nApr 09 11:58:38 ======================================================================\r\nApr 09 11:58:38 ERROR [100.118s]: test_check_failed_messages (__main__.FaultyAgentRpcTestWithSpawn)\r\nApr 09 11:58:38 ----------------------------------------------------------------------\r\nApr 09 11:58:38 Traceback (most recent call last):\r\nApr 09 11:58:38   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 175, in wrapper\r\nApr 09 11:58:38     self._join_processes(fn)\r\nApr 09 11:58:38   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 285, in _join_processes\r\nApr 09 11:58:38     self._check_return_codes(elapsed_time)\r\nApr 09 11:58:38   File \"/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/testing/_internal/common_distributed.py\", line 323, in _check_return_codes\r\nApr 09 11:58:38     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))\r\nApr 09 11:58:38 RuntimeError: Process 1 terminated or timed out after 100.0106930732727 seconds\r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/35575",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/35575/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/35575/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/35575/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/35575",
      "id": 589428376,
      "node_id": "MDU6SXNzdWU1ODk0MjgzNzY=",
      "number": 35575,
      "title": "DISABLED test_debug_info (__main__.DistAutogradTestWithSpawn)",
      "user": {
        "login": "xush6528",
        "id": 7608630,
        "node_id": "MDQ6VXNlcjc2MDg2MzA=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/7608630?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/xush6528",
        "html_url": "https://github.com/xush6528",
        "followers_url": "https://api.github.com/users/xush6528/followers",
        "following_url": "https://api.github.com/users/xush6528/following{/other_user}",
        "gists_url": "https://api.github.com/users/xush6528/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/xush6528/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/xush6528/subscriptions",
        "organizations_url": "https://api.github.com/users/xush6528/orgs",
        "repos_url": "https://api.github.com/users/xush6528/repos",
        "events_url": "https://api.github.com/users/xush6528/events{/privacy}",
        "received_events_url": "https://api.github.com/users/xush6528/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1536612774,
          "node_id": "MDU6TGFiZWwxNTM2NjEyNzc0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20rpc",
          "name": "module: rpc",
          "color": "f7e101",
          "default": false,
          "description": "Related to RPC, distributed autograd, RRef, and distributed optimizer"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 2,
      "created_at": "2020-03-27T21:44:25Z",
      "updated_at": "2020-05-11T01:38:23Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "Saw 2 instances on test, pytorch_linux_xenial_py3_6_gcc5_4_test\r\n\r\nhttps://app.circleci.com/pipelines/github/pytorch/pytorch/147576/workflows/ee6a83a9-b219-488c-8224-b1d8404ad9f1/jobs/4978490\r\n\r\nhttps://app.circleci.com/pipelines/github/pytorch/pytorch/147327/workflows/b0fd43f7-d18a-4b47-a6c2-8c881c1cac63/jobs/4972041\n\ncc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/40391",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/40391/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/40391/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/40391/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/40391",
      "id": 643299967,
      "node_id": "MDU6SXNzdWU2NDMyOTk5Njc=",
      "number": 40391,
      "title": "Mkldnn modules should throw RuntimeErrors if invoked when mkldnn is disabled",
      "user": {
        "login": "ngimel",
        "id": 15841449,
        "node_id": "MDQ6VXNlcjE1ODQxNDQ5",
        "avatar_url": "https://avatars3.githubusercontent.com/u/15841449?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ngimel",
        "html_url": "https://github.com/ngimel",
        "followers_url": "https://api.github.com/users/ngimel/followers",
        "following_url": "https://api.github.com/users/ngimel/following{/other_user}",
        "gists_url": "https://api.github.com/users/ngimel/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ngimel/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ngimel/subscriptions",
        "organizations_url": "https://api.github.com/users/ngimel/orgs",
        "repos_url": "https://api.github.com/users/ngimel/repos",
        "events_url": "https://api.github.com/users/ngimel/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ngimel/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1303456553,
          "node_id": "MDU6TGFiZWwxMzAzNDU2NTUz",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20mkldnn",
          "name": "module: mkldnn",
          "color": "f7e101",
          "default": false,
          "description": "Related to Intel IDEEP/MKL-DNN (mkldnn) integration"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "XiaobingSuper",
        "id": 16217777,
        "node_id": "MDQ6VXNlcjE2MjE3Nzc3",
        "avatar_url": "https://avatars1.githubusercontent.com/u/16217777?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/XiaobingSuper",
        "html_url": "https://github.com/XiaobingSuper",
        "followers_url": "https://api.github.com/users/XiaobingSuper/followers",
        "following_url": "https://api.github.com/users/XiaobingSuper/following{/other_user}",
        "gists_url": "https://api.github.com/users/XiaobingSuper/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/XiaobingSuper/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/XiaobingSuper/subscriptions",
        "organizations_url": "https://api.github.com/users/XiaobingSuper/orgs",
        "repos_url": "https://api.github.com/users/XiaobingSuper/repos",
        "events_url": "https://api.github.com/users/XiaobingSuper/events{/privacy}",
        "received_events_url": "https://api.github.com/users/XiaobingSuper/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "XiaobingSuper",
          "id": 16217777,
          "node_id": "MDQ6VXNlcjE2MjE3Nzc3",
          "avatar_url": "https://avatars1.githubusercontent.com/u/16217777?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/XiaobingSuper",
          "html_url": "https://github.com/XiaobingSuper",
          "followers_url": "https://api.github.com/users/XiaobingSuper/followers",
          "following_url": "https://api.github.com/users/XiaobingSuper/following{/other_user}",
          "gists_url": "https://api.github.com/users/XiaobingSuper/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/XiaobingSuper/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/XiaobingSuper/subscriptions",
          "organizations_url": "https://api.github.com/users/XiaobingSuper/orgs",
          "repos_url": "https://api.github.com/users/XiaobingSuper/repos",
          "events_url": "https://api.github.com/users/XiaobingSuper/events{/privacy}",
          "received_events_url": "https://api.github.com/users/XiaobingSuper/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 1,
      "created_at": "2020-06-22T19:10:06Z",
      "updated_at": "2020-06-23T05:59:33Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "Currently the following script will succeed:\r\n```\r\nimport torch\r\nimport copy\r\nfrom torch.utils import mkldnn as mkldnn_utils\r\ngroups=1\r\nN = 32\r\nC = 32\r\nM = 32\r\nx = torch.randn(N, C, 56, 56, dtype=torch.float).to_mkldnn()\r\nconv2d = torch.nn.Conv2d(in_channels=C,\r\n                            out_channels=M,\r\n                            kernel_size=3,\r\n                            padding=1)\r\nmkldnn_conv2d = mkldnn_utils.to_mkldnn(copy.deepcopy(conv2d))\r\nwith torch.backends.mkldnn.flags(enabled=False):\r\n    y_mkldnn = mkldnn_conv2d(x).to_dense()\r\n```\r\nIt is confusing that when mkldnn is disabled, one can still call mkldnn functions. An attempt to do so should throw a RuntimeError. \r\n\n\ncc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @VitalyFedyunin",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/37495",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/37495/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/37495/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/37495/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/37495",
      "id": 608912043,
      "node_id": "MDU6SXNzdWU2MDg5MTIwNDM=",
      "number": 37495,
      "title": "DISABLED test_default_quantized_lstm (quantization.test_quantize.TestPostTrainingDynamic)",
      "user": {
        "login": "mruberry",
        "id": 38511765,
        "node_id": "MDQ6VXNlcjM4NTExNzY1",
        "avatar_url": "https://avatars3.githubusercontent.com/u/38511765?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mruberry",
        "html_url": "https://github.com/mruberry",
        "followers_url": "https://api.github.com/users/mruberry/followers",
        "following_url": "https://api.github.com/users/mruberry/following{/other_user}",
        "gists_url": "https://api.github.com/users/mruberry/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mruberry/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mruberry/subscriptions",
        "organizations_url": "https://api.github.com/users/mruberry/orgs",
        "repos_url": "https://api.github.com/users/mruberry/repos",
        "events_url": "https://api.github.com/users/mruberry/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mruberry/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 1031340614,
          "node_id": "MDU6TGFiZWwxMDMxMzQwNjE0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/quantization",
          "name": "quantization",
          "color": "f7e101",
          "default": false,
          "description": "Quantization support in PyTorch"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "raghuramank100",
        "id": 48835916,
        "node_id": "MDQ6VXNlcjQ4ODM1OTE2",
        "avatar_url": "https://avatars1.githubusercontent.com/u/48835916?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/raghuramank100",
        "html_url": "https://github.com/raghuramank100",
        "followers_url": "https://api.github.com/users/raghuramank100/followers",
        "following_url": "https://api.github.com/users/raghuramank100/following{/other_user}",
        "gists_url": "https://api.github.com/users/raghuramank100/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/raghuramank100/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/raghuramank100/subscriptions",
        "organizations_url": "https://api.github.com/users/raghuramank100/orgs",
        "repos_url": "https://api.github.com/users/raghuramank100/repos",
        "events_url": "https://api.github.com/users/raghuramank100/events{/privacy}",
        "received_events_url": "https://api.github.com/users/raghuramank100/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "raghuramank100",
          "id": 48835916,
          "node_id": "MDQ6VXNlcjQ4ODM1OTE2",
          "avatar_url": "https://avatars1.githubusercontent.com/u/48835916?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/raghuramank100",
          "html_url": "https://github.com/raghuramank100",
          "followers_url": "https://api.github.com/users/raghuramank100/followers",
          "following_url": "https://api.github.com/users/raghuramank100/following{/other_user}",
          "gists_url": "https://api.github.com/users/raghuramank100/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/raghuramank100/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/raghuramank100/subscriptions",
          "organizations_url": "https://api.github.com/users/raghuramank100/orgs",
          "repos_url": "https://api.github.com/users/raghuramank100/repos",
          "events_url": "https://api.github.com/users/raghuramank100/events{/privacy}",
          "received_events_url": "https://api.github.com/users/raghuramank100/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 1,
      "created_at": "2020-04-29T09:33:17Z",
      "updated_at": "2020-05-12T03:55:54Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "This test is failing intermittently on multiple builds with increasing frequency recently and no clear cause. \r\n\r\n```\r\nApr 29 09:14:17 ======================================================================\r\nApr 29 09:14:17 ERROR [0.030s]: test_default_quantized_lstm (quantization.test_quantize.TestPostTrainingDynamic)\r\nApr 29 09:14:17 ----------------------------------------------------------------------\r\nApr 29 09:14:17 Traceback (most recent call last):\r\nApr 29 09:14:17   File \"/var/lib/jenkins/workspace/test/quantization/test_quantize.py\", line 862, in test_default_quantized_lstm\r\nApr 29 09:14:17     y, (h, c) = cell_dq(x, (h, c))\r\nApr 29 09:14:17   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 562, in __call__\r\nApr 29 09:14:17     result = self.forward(*input, **kwargs)\r\nApr 29 09:14:17   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 351, in forward\r\nApr 29 09:14:17     return self.forward_tensor(input, hx)\r\nApr 29 09:14:17   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 312, in forward_tensor\r\nApr 29 09:14:17     input, hx, batch_sizes, max_batch_size, sorted_indices)\r\nApr 29 09:14:17   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 293, in forward_impl\r\nApr 29 09:14:17     self.batch_first, dtype=self.dtype, use_dynamic=True)\r\nApr 29 09:14:17 RuntimeError: In ChooseQuantizationParams, min should be less than or equal to max\r\n```\r\n\n\ncc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34658",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34658/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34658/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34658/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34658",
      "id": 580112392,
      "node_id": "MDU6SXNzdWU1ODAxMTIzOTI=",
      "number": 34658,
      "title": "DISABLED test_keypoint_rcnn (__main__.TestONNXRuntime_opset11)",
      "user": {
        "login": "eellison",
        "id": 11477974,
        "node_id": "MDQ6VXNlcjExNDc3OTc0",
        "avatar_url": "https://avatars2.githubusercontent.com/u/11477974?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/eellison",
        "html_url": "https://github.com/eellison",
        "followers_url": "https://api.github.com/users/eellison/followers",
        "following_url": "https://api.github.com/users/eellison/following{/other_user}",
        "gists_url": "https://api.github.com/users/eellison/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/eellison/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/eellison/subscriptions",
        "organizations_url": "https://api.github.com/users/eellison/orgs",
        "repos_url": "https://api.github.com/users/eellison/repos",
        "events_url": "https://api.github.com/users/eellison/events{/privacy}",
        "received_events_url": "https://api.github.com/users/eellison/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 693805995,
          "node_id": "MDU6TGFiZWw2OTM4MDU5OTU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20onnx",
          "name": "module: onnx",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.onnx"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 5,
      "created_at": "2020-03-12T17:48:30Z",
      "updated_at": "2020-03-13T17:59:05Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "## 🐛 Bug\r\n\r\nhttps://app.circleci.com/pipelines/github/pytorch/pytorch/138566/workflows/850299ec-3258-4e78-b680-cfad253c746a/jobs/4782754/parallel-runs/0/steps/0-105\r\n\r\n```\r\nMar 12 17:35:27 =================================== FAILURES ===================================\r\nMar 12 17:35:27 __________________ TestONNXRuntime_opset11.test_keypoint_rcnn __________________\r\nMar 12 17:35:27 \r\nMar 12 17:35:27 self = <test_pytorch_onnx_onnxruntime.TestONNXRuntime_opset11 testMethod=test_keypoint_rcnn>\r\nMar 12 17:35:27 \r\nMar 12 17:35:27     def wrapper(self):\r\nMar 12 17:35:27         if self.opset_version < min_opset_version:\r\nMar 12 17:35:27             raise unittest.SkipTest(\"Skip verify test for unsupported opset_version\")\r\nMar 12 17:35:27 >       return func(self)\r\nMar 12 17:35:27 \r\nMar 12 17:35:27 test/onnx/test_pytorch_common.py:54: \r\n```\r\n\n\ncc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/37409",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/37409/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/37409/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/37409/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/37409",
      "id": 608167791,
      "node_id": "MDU6SXNzdWU2MDgxNjc3OTE=",
      "number": 37409,
      "title": "Compatibility of subset dataset with disabled batch sampling",
      "user": {
        "login": "dvirginz",
        "id": 31047807,
        "node_id": "MDQ6VXNlcjMxMDQ3ODA3",
        "avatar_url": "https://avatars2.githubusercontent.com/u/31047807?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/dvirginz",
        "html_url": "https://github.com/dvirginz",
        "followers_url": "https://api.github.com/users/dvirginz/followers",
        "following_url": "https://api.github.com/users/dvirginz/following{/other_user}",
        "gists_url": "https://api.github.com/users/dvirginz/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/dvirginz/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/dvirginz/subscriptions",
        "organizations_url": "https://api.github.com/users/dvirginz/orgs",
        "repos_url": "https://api.github.com/users/dvirginz/repos",
        "events_url": "https://api.github.com/users/dvirginz/events{/privacy}",
        "received_events_url": "https://api.github.com/users/dvirginz/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1076923878,
          "node_id": "MDU6TGFiZWwxMDc2OTIzODc4",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20dataloader",
          "name": "module: dataloader",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.utils.data.DataLoader and Sampler"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 3,
      "created_at": "2020-04-28T09:32:27Z",
      "updated_at": "2020-04-29T07:52:13Z",
      "closed_at": null,
      "author_association": "NONE",
      "active_lock_reason": null,
      "body": "I think there is a compatibility issue with disabled batch sampling and subset dataset\r\nThe use-case - define custom batch sampling, and split the dataset using PyTorch split utility function\r\nHere's a minimal working example\r\n```\r\nself.train_dataset, self.val_dataset, self.test_dataset = torch.utils.data.random_split(\r\n            self.dataset, [100, 100, 100])\r\n\r\nloader = DataLoader(\r\n                dataset=self.train_dataset,\r\n                batch_size=None,\r\n                batch_sampler=None,\r\n                sampler=BatchSampler(\r\n                    SequentialSampler(dataset), batch_size=self.hparams.batch_size, drop_last=False),\r\n                num_workers=self.hparams.num_data_workers,\r\n            )\r\n```\r\nAnd when iterating the subset datasets this is the error\r\n```\r\nException has occurred: TypeError\r\nlist indices must be integers or slices, not list\r\n  File \"/path/utils/data/dataset.py\", line 257, in __getitem__\r\n    return self.dataset[self.indices[idx]]\r\n  File \"/path/utils/data/_utils/fetch.py\", line 46, in fetch\r\n    data = self.dataset[possibly_batched_index]\r\n  File \"/path/utils/data/dataloader.py\", line 385, in _next_data\r\n    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration\r\n  File \"/path/utils/data/dataloader.py\", line 345, in __next__\r\n    data = self._next_data()\r\n  File \"/path/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py\", line 251, in _evaluate\r\n    for batch_idx, batch in enumerate(dataloader):\r\n  File \"/path/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py\", line 843, in run_pretrain_routine\r\n    False)\r\n  File \"/path/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_parts.py\", line 477, in single_gpu_train\r\n    self.run_pretrain_routine(model)\r\n  File \"/path/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py\", line 704, in fit\r\n    self.single_gpu_train(model)\r\n  File \"/path/train.py\", line 152, in main_train\r\n    trainer.fit(model)\r\n  File \"/path/train.py\", line 66, in main\r\n    main_train(model_class_pointer, hyperparams, logger)\r\n  File \"/path/train.py\", line 161, in <module>\r\n    main()\r\n  File \"/path/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/path/lib/python3.7/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/path/lib/python3.7/runpy.py\", line 263, in run_path\r\n    pkg_name=pkg_name, script_name=fname)\r\n  File \"/path/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/path/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\r\n    \"__main__\", mod_spec)\r\n```\r\n\r\nAs the self.indices of the `subset` object is a simple python list.\r\n\r\nPlease refer to the forum post, where @ptrblck  approves reproducing the bug and offering a workaround.\n\ncc @SsnL",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/32644",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/32644/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/32644/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/32644/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/32644",
      "id": 555422490,
      "node_id": "MDU6SXNzdWU1NTU0MjI0OTA=",
      "number": 32644,
      "title": "DISABLED test_quantized_rnn (test_quanization.PostTrainingDynamicQuantTest)",
      "user": {
        "login": "rohan-varma",
        "id": 8039770,
        "node_id": "MDQ6VXNlcjgwMzk3NzA=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/8039770?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rohan-varma",
        "html_url": "https://github.com/rohan-varma",
        "followers_url": "https://api.github.com/users/rohan-varma/followers",
        "following_url": "https://api.github.com/users/rohan-varma/following{/other_user}",
        "gists_url": "https://api.github.com/users/rohan-varma/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rohan-varma/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rohan-varma/subscriptions",
        "organizations_url": "https://api.github.com/users/rohan-varma/orgs",
        "repos_url": "https://api.github.com/users/rohan-varma/repos",
        "events_url": "https://api.github.com/users/rohan-varma/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rohan-varma/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1031340614,
          "node_id": "MDU6TGFiZWwxMDMxMzQwNjE0",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/quantization",
          "name": "quantization",
          "color": "f7e101",
          "default": false,
          "description": "Quantization support in PyTorch"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "z-a-f",
        "id": 4216323,
        "node_id": "MDQ6VXNlcjQyMTYzMjM=",
        "avatar_url": "https://avatars2.githubusercontent.com/u/4216323?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/z-a-f",
        "html_url": "https://github.com/z-a-f",
        "followers_url": "https://api.github.com/users/z-a-f/followers",
        "following_url": "https://api.github.com/users/z-a-f/following{/other_user}",
        "gists_url": "https://api.github.com/users/z-a-f/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/z-a-f/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/z-a-f/subscriptions",
        "organizations_url": "https://api.github.com/users/z-a-f/orgs",
        "repos_url": "https://api.github.com/users/z-a-f/repos",
        "events_url": "https://api.github.com/users/z-a-f/events{/privacy}",
        "received_events_url": "https://api.github.com/users/z-a-f/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "z-a-f",
          "id": 4216323,
          "node_id": "MDQ6VXNlcjQyMTYzMjM=",
          "avatar_url": "https://avatars2.githubusercontent.com/u/4216323?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/z-a-f",
          "html_url": "https://github.com/z-a-f",
          "followers_url": "https://api.github.com/users/z-a-f/followers",
          "following_url": "https://api.github.com/users/z-a-f/following{/other_user}",
          "gists_url": "https://api.github.com/users/z-a-f/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/z-a-f/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/z-a-f/subscriptions",
          "organizations_url": "https://api.github.com/users/z-a-f/orgs",
          "repos_url": "https://api.github.com/users/z-a-f/repos",
          "events_url": "https://api.github.com/users/z-a-f/events{/privacy}",
          "received_events_url": "https://api.github.com/users/z-a-f/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 15,
      "created_at": "2020-01-27T08:22:49Z",
      "updated_at": "2020-03-06T03:05:33Z",
      "closed_at": null,
      "author_association": "MEMBER",
      "active_lock_reason": null,
      "body": "## 🐛 Bug\r\n\r\ntes_quantized_rnn is flaky, see https://app.circleci.com/jobs/github/pytorch/pytorch/4343194\r\nSee example failure: \r\n```\r\nJan 26 08:10:23 ======================================================================\r\nJan 26 08:10:23 ERROR [0.186s]: test_quantized_rnn (__main__.PostTrainingDynamicQuantTest)\r\nJan 26 08:10:23 ----------------------------------------------------------------------\r\nJan 26 08:10:23 Traceback (most recent call last):\r\nJan 26 08:10:23   File \"test_quantization.py\", line 722, in test_quantized_rnn\r\nJan 26 08:10:23     y, (h, c) = cell_dq(x, (h, c))\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 540, in __call__\r\nJan 26 08:10:23     result = self.forward(*input, **kwargs)\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 373, in forward\r\nJan 26 08:10:23     return self.forward_tensor(input, hx)\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 334, in forward_tensor\r\nJan 26 08:10:23     input, hx, batch_sizes, max_batch_size, sorted_indices)\r\nJan 26 08:10:23   File \"/opt/conda/lib/python3.6/site-packages/torch/nn/quantized/dynamic/modules/rnn.py\", line 315, in forward_impl\r\nJan 26 08:10:23     self.batch_first, dtype=self.dtype, use_dynamic=True)\r\nJan 26 08:10:23 RuntimeError: quantization scale should be > 0\r\n```\n\ncc @ezyang @gchanan @zou3519 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34213",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34213/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34213/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34213/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34213",
      "id": 575502768,
      "node_id": "MDU6SXNzdWU1NzU1MDI3Njg=",
      "number": 34213,
      "title": "DISABLED test_script_pack_padded_sequence (test_jit.TestScript)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953983,
          "node_id": "MDU6TGFiZWw2Nzk5NTM5ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/jit",
          "name": "jit",
          "color": "c5def5",
          "default": false,
          "description": null
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-03-04T15:29:15Z",
      "updated_at": "2020-03-09T17:09:59Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "Previous failed runs:\r\nhttps://circleci.com/gh/pytorch/pytorch/4682966\r\n\r\nSubsequent succeeded runs:\r\nhttps://circleci.com/gh/pytorch/pytorch/4682247\r\nhttps://circleci.com/gh/pytorch/pytorch/4682241\r\n\r\nToday, it consistently fails:\r\nhttps://circleci.com/gh/pytorch/pytorch/4687625\r\nhttps://circleci.com/gh/pytorch/pytorch/4687610\r\nhttps://circleci.com/gh/pytorch/pytorch/4686149\r\n\r\n@ljk53 tried reverting the seemingly culprit PR #32814 and #34055, but the error persist. \r\n\r\nI am going to disable this test while JIT team investigating it. \n\ncc @ezyang @gchanan @zou3519 @suo",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/34432",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/34432/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/34432/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/34432/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/34432",
      "id": 577434425,
      "node_id": "MDU6SXNzdWU1Nzc0MzQ0MjU=",
      "number": 34432,
      "title": "DISABLED test_gloo_backend_1gpu_module_device_ids_integer_list (__main__.DistributedDataParallelTest)",
      "user": {
        "login": "mrshenli",
        "id": 16999635,
        "node_id": "MDQ6VXNlcjE2OTk5NjM1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/16999635?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/mrshenli",
        "html_url": "https://github.com/mrshenli",
        "followers_url": "https://api.github.com/users/mrshenli/followers",
        "following_url": "https://api.github.com/users/mrshenli/following{/other_user}",
        "gists_url": "https://api.github.com/users/mrshenli/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/mrshenli/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mrshenli/subscriptions",
        "organizations_url": "https://api.github.com/users/mrshenli/orgs",
        "repos_url": "https://api.github.com/users/mrshenli/repos",
        "events_url": "https://api.github.com/users/mrshenli/events{/privacy}",
        "received_events_url": "https://api.github.com/users/mrshenli/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 443484135,
          "node_id": "MDU6TGFiZWw0NDM0ODQxMzU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/high%20priority",
          "name": "high priority",
          "color": "F22613",
          "default": false,
          "description": null
        },
        {
          "id": 679953883,
          "node_id": "MDU6TGFiZWw2Nzk5NTM4ODM=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/module:%20distributed",
          "name": "module: distributed",
          "color": "f7e101",
          "default": false,
          "description": "Related to torch.distributed"
        },
        {
          "id": 1301397902,
          "node_id": "MDU6TGFiZWwxMzAxMzk3OTAy",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/topic:%20flaky-tests",
          "name": "topic: flaky-tests",
          "color": "0e8a16",
          "default": false,
          "description": "Problem is a flaky test in CI"
        },
        {
          "id": 466131885,
          "node_id": "MDU6TGFiZWw0NjYxMzE4ODU=",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triage%20review",
          "name": "triage review",
          "color": "cc317c",
          "default": false,
          "description": ""
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": {
        "login": "pritamdamania87",
        "id": 9958665,
        "node_id": "MDQ6VXNlcjk5NTg2NjU=",
        "avatar_url": "https://avatars1.githubusercontent.com/u/9958665?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/pritamdamania87",
        "html_url": "https://github.com/pritamdamania87",
        "followers_url": "https://api.github.com/users/pritamdamania87/followers",
        "following_url": "https://api.github.com/users/pritamdamania87/following{/other_user}",
        "gists_url": "https://api.github.com/users/pritamdamania87/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/pritamdamania87/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pritamdamania87/subscriptions",
        "organizations_url": "https://api.github.com/users/pritamdamania87/orgs",
        "repos_url": "https://api.github.com/users/pritamdamania87/repos",
        "events_url": "https://api.github.com/users/pritamdamania87/events{/privacy}",
        "received_events_url": "https://api.github.com/users/pritamdamania87/received_events",
        "type": "User",
        "site_admin": false
      },
      "assignees": [
        {
          "login": "pritamdamania87",
          "id": 9958665,
          "node_id": "MDQ6VXNlcjk5NTg2NjU=",
          "avatar_url": "https://avatars1.githubusercontent.com/u/9958665?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/pritamdamania87",
          "html_url": "https://github.com/pritamdamania87",
          "followers_url": "https://api.github.com/users/pritamdamania87/followers",
          "following_url": "https://api.github.com/users/pritamdamania87/following{/other_user}",
          "gists_url": "https://api.github.com/users/pritamdamania87/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/pritamdamania87/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/pritamdamania87/subscriptions",
          "organizations_url": "https://api.github.com/users/pritamdamania87/orgs",
          "repos_url": "https://api.github.com/users/pritamdamania87/repos",
          "events_url": "https://api.github.com/users/pritamdamania87/events{/privacy}",
          "received_events_url": "https://api.github.com/users/pritamdamania87/received_events",
          "type": "User",
          "site_admin": false
        }
      ],
      "milestone": null,
      "comments": 0,
      "created_at": "2020-03-08T02:42:25Z",
      "updated_at": "2020-05-06T21:19:46Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/20231//console\r\n\r\n```\r\n22:09:03 ======================================================================\r\n22:09:03 FAIL: test_gloo_backend_1gpu_module_device_ids_integer_list (__main__.DistributedDataParallelTest)\r\n22:09:03 ----------------------------------------------------------------------\r\n22:09:03 Traceback (most recent call last):\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 175, in wrapper\r\n22:09:03     self._join_processes(fn)\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 256, in _join_processes\r\n22:09:03     self._check_return_codes(elapsed_time)\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py\", line 276, in _check_return_codes\r\n22:09:03     self.assertEqual(p.exitcode, first_process.exitcode)\r\n22:09:03   File \"/var/lib/jenkins/.local/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py\", line 915, in assertEqual\r\n22:09:03     super(TestCase, self).assertLessEqual(abs(x - y), prec, message)\r\n22:09:03 AssertionError: 16 not less than or equal to 1e-05 : \r\n```\n\ncc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar",
      "score": 0.0
    },
    {
      "url": "https://api.github.com/repos/pytorch/pytorch/issues/31750",
      "repository_url": "https://api.github.com/repos/pytorch/pytorch",
      "labels_url": "https://api.github.com/repos/pytorch/pytorch/issues/31750/labels{/name}",
      "comments_url": "https://api.github.com/repos/pytorch/pytorch/issues/31750/comments",
      "events_url": "https://api.github.com/repos/pytorch/pytorch/issues/31750/events",
      "html_url": "https://github.com/pytorch/pytorch/issues/31750",
      "id": 544251558,
      "node_id": "MDU6SXNzdWU1NDQyNTE1NTg=",
      "number": 31750,
      "title": "DISABLED test/onnx/test_pytorch_onnx_onnxruntime.py::TestONNXRuntime_opset10::test_interpolate_downsample",
      "user": {
        "login": "Krovatkin",
        "id": 5086322,
        "node_id": "MDQ6VXNlcjUwODYzMjI=",
        "avatar_url": "https://avatars0.githubusercontent.com/u/5086322?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Krovatkin",
        "html_url": "https://github.com/Krovatkin",
        "followers_url": "https://api.github.com/users/Krovatkin/followers",
        "following_url": "https://api.github.com/users/Krovatkin/following{/other_user}",
        "gists_url": "https://api.github.com/users/Krovatkin/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Krovatkin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Krovatkin/subscriptions",
        "organizations_url": "https://api.github.com/users/Krovatkin/orgs",
        "repos_url": "https://api.github.com/users/Krovatkin/repos",
        "events_url": "https://api.github.com/users/Krovatkin/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Krovatkin/received_events",
        "type": "User",
        "site_admin": false
      },
      "labels": [
        {
          "id": 1679533716,
          "node_id": "MDU6TGFiZWwxNjc5NTMzNzE2",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/skipped",
          "name": "skipped",
          "color": "bfdadc",
          "default": false,
          "description": "Denotes a (flaky) test currently skipped in CI."
        },
        {
          "id": 1301347167,
          "node_id": "MDU6TGFiZWwxMzAxMzQ3MTY3",
          "url": "https://api.github.com/repos/pytorch/pytorch/labels/triaged",
          "name": "triaged",
          "color": "006b75",
          "default": false,
          "description": "This issue has been looked at a team member, and triaged and prioritized into an appropriate module"
        }
      ],
      "state": "open",
      "locked": false,
      "assignee": null,
      "assignees": [

      ],
      "milestone": null,
      "comments": 2,
      "created_at": "2019-12-31T19:03:16Z",
      "updated_at": "2020-01-02T14:49:19Z",
      "closed_at": null,
      "author_association": "CONTRIBUTOR",
      "active_lock_reason": null,
      "body": "Temporarily disabling a flakey test.",
      "score": 0.0
    }
  ]
}
